<a href="https://colab.research.google.com/github/asirabm/cctv-video-anomaly-detection/blob/main/02_video_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Dataset Acquisition and Inspection**

In [7]:
!pip install -q huggingface_hub

In [8]:
from huggingface_hub import HfApi

repo_id = "jinmang2/ucf_crime"
api = HfApi()
files = api.list_repo_files(
    repo_id=repo_id,
    repo_type="dataset"
)

print("Total files:", len(files))

for file in files:
    print(file)

Total files: 24
.gitattributes
Anomaly-Videos-Part-1.zip
Anomaly-Videos-Part-2.zip
Anomaly-Videos-Part-3.zip
Anomaly-Videos-Part-4.zip
Normal_Videos_for_Event_Recognition.zip
README.md
Testing_Normal_Videos.zip
Training-Normal-Videos-Part-1.zip
Training-Normal-Videos-Part-2.zip
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/ClassIDs.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/test_001.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/test_002.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/test_003.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/test_004.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/train_001.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/train_002.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/train_003.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/train_004.txt
UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/Anomaly_Test.txt
UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/Anomaly_Train.txt
UCF_Crimes-Train-Test-Split/Temporal_Anomaly_Annotation_for_Testing_Videos.txt
test.zip
ucf_crime.py

In [9]:
from huggingface_hub import hf_hub_download

readme_path = hf_hub_download(
    repo_id=repo_id,
    filename="README.md",
    repo_type="dataset"
)

with open(readme_path, "r", encoding="utf-8") as file:
    readme_text = file.read()

print(readme_text[:12000])

README.md:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

---
license: cc0-1.0
task_categories:
- video-classification
language:
- en
pretty_name: ucf_crime
configs:
- config_name: anomaly
  data_files:
    - split: train
      path: "data/anomaly-train-*.tar" # 1610 samples (1081 + 24 + 120 + 118 + 125 + 142)
    - split: test
      path: "data/anomaly-test-*.tar" # 290 samples (119 + 4 + 48 + 50 + 43 + 26)
- config_name: event1
  data_files:
    - split: train
      path:
        - "data/*-event-train-*.tar" # common 28 samples (anomaly-train:anomaly-test=24:4)
        - "data/*-event-test-2-*.tar"
        - "data/*-event-test-3-*.tar"
        - "data/*-event-test-4-*.tar"
    - split: test
      path: "data/*-event-test-1-*.tar" # 168 samples (anomaly-train:anomaly-test=120:48)
- config_name: event2
  data_files:
    - split: train
      path:
        - "data/*-event-train-*.tar"
        - "data/*-event-test-1-*.tar"
        - "data/*-event-test-3-*.tar"
        - "data/*-event-test-4-*.tar"
    - split: test
      path: "data/*-event-test-2-*.tar" # 168 samples (anomaly-train:anomaly-test=118:50)
- config_name: event3
  data_files:
    - split: train
      path:
        - "data/*-event-train-*.tar"
        - "data/*-event-test-1-*.tar"
        - "data/*-event-test-2-*.tar"
        - "data/*-event-test-4-*.tar"
    - split: test
      path: "data/*-event-test-3-*.tar" # 168 samples (anomaly-train:anomaly-test=125:43)
- config_name: event4
  data_files:
    - split: train
      path:
        - "data/*-event-train-*.tar"
        - "data/*-event-test-1-*.tar"
        - "data/*-event-test-2-*.tar"
        - "data/*-event-test-3-*.tar"
    - split: test
      path: "data/*-event-test-4-*.tar" # 168 samples (anomaly-train:anomaly-test=142:26)
size_categories:
- 10M<n<100M
---


# UCF-Crime Dataset (WebDataset Format)

이 데이터셋은 [UCF-Crime](https://www.crcv.ucf.edu/projects/real-world/) 데이터셋을 Hugging Face `datasets` 라이브러리의 스트리밍 기능을 위해 WebDataset(TAR Sharding) 형식으로 변환한 버전입니다.
100GB 이상의 대규모 비디오 데이터를 효율적으로 로드할 수 있습니다.

## Dataset Description
- **Homepage:** [CRCV UCF-Crime](https://www.crcv.ucf.edu/projects/real-world/)
- **Paper:** [Real-world Anomaly Detection in Surveillance Videos](https://arxiv.org/abs/1801.04264)


```python
from datasets import load_dataset

# Anomaly Detection 설정 로드
dataset = load_dataset("your_id/ucf_crime", "anomaly_detection", split="train", streaming=True)

for sample in dataset:
    video_path = sample["mp4"]
    label = sample["json"]["event"]
    print(f"Video loaded: {video_path}, Label: {label}")
    break
```

```
@InProceedings{Sultani_2018_CVPR,
    author={Sultani, Waqas and Chen, Chen and Shah, Mubarak},
    title={Real-World Anomaly Detection in Surveillance Videos},
    booktitle={The IEEE Conference on Computer Vision and Pattern Recognition (CVPR)},
    month={June},
    year={2018},
}
```

**Create the Drive folders to store npy files**

In [10]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [11]:
from google.colab import drive
import os

drive.mount('/content/drive')

project_path = '/content/drive/MyDrive/UCF_Crime_Project'

os.makedirs(project_path + '/features/train', exist_ok=True)
os.makedirs(project_path + '/features/test', exist_ok=True)
os.makedirs(project_path + '/metadata', exist_ok=True)

print("Project folders are ready.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project folders are ready.

In [12]:
from huggingface_hub import hf_hub_download

repo_id = "jinmang2/ucf_crime"
file_name = "Anomaly-Videos-Part-1.zip"

zip_path = hf_hub_download(
    repo_id=repo_id,
    filename=file_name,
    repo_type="dataset",
    local_dir="/content/UCF_Crime"
)

print("sucessfully Downloded.")

Anomaly-Videos-Part-1.zip: reconstructing file:   0%|          |  0.00B / 6.27GB

Anomaly-Videos-Part-1.zip: downloading bytes:           |  0.00B

sucessfully Downloded.

**Insepect Downloaded folder part 1**

In [13]:
import zipfile

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    files = zip_ref.namelist()

print("Total files in ZIP:", len(files))

print("First 30 files:")
for file in files[:30]:
    print(file)

Total files in ZIP: 205
First 30 files:
Anomaly-Videos-Part-1/
Anomaly-Videos-Part-1/Abuse/
Anomaly-Videos-Part-1/Abuse/Abuse041_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse037_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse012_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse001_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse048_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse003_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse006_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse020_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse018_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse025_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse029_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse042_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse032_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse045_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse049_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse026_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse044_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse031_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse005_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse015_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse038_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse033_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse047_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse008_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse010_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse007_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse022_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse028_x264.mp4

**count the video file**

In [14]:
video_files = [
    file for file in files
    if file.lower().endswith('.mp4')
]

print("Total video files:", len(video_files))

print("\nFirst 10 video files:")
for file in video_files[:10]:
    print(file)

Total video files: 200

First 10 video files:
Anomaly-Videos-Part-1/Abuse/Abuse041_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse037_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse012_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse001_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse048_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse003_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse006_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse020_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse018_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse025_x264.mp4

**Inspect non video files **

In [15]:
other_files = [
    file for file in files
    if not file.lower().endswith('.mp4')
]

print("Other entries:", len(other_files))

for file in other_files:
    print(file)

Other entries: 5
Anomaly-Videos-Part-1/
Anomaly-Videos-Part-1/Abuse/
Anomaly-Videos-Part-1/Assault/
Anomaly-Videos-Part-1/Arrest/
Anomaly-Videos-Part-1/Arson/

**Extract the videos from zip file **

In [16]:
import zipfile
import os

extract_path = "/content/UCF_Crime/videos"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction completed.")
print("Videos extracted to:", extract_path)

Extraction completed.
Videos extracted to: /content/UCF_Crime/videos

**Check the extracted videos**

In [17]:
import os

video_root = "/content/UCF_Crime/videos/Anomaly-Videos-Part-1"

extracted_videos = []

for root, dirs, filenames in os.walk(video_root):
    for filename in filenames:
        if filename.lower().endswith(".mp4"):
            extracted_videos.append(
                os.path.join(root, filename)
            )

print("Extracted MP4 videos:", len(extracted_videos))

print("\nFirst 10 videos:")
for video in extracted_videos[:10]:
    print(video)

Extracted MP4 videos: 200

First 10 videos:
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault030_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault034_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault004_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault041_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault011_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault038_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault040_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault023_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault013_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault019_x264.mp4

**Count videos in each category**

In [18]:
from collections import Counter
import os

category_counts = Counter()

for video in extracted_videos:
    category = os.path.basename(os.path.dirname(video))
    category_counts[category] += 1

print("Videos in each category:")

for category, count in sorted(category_counts.items()):
    print(f"{category}: {count}")

print("Total videos:", sum(category_counts.values()))

Videos in each category:
Abuse: 50
Arrest: 50
Arson: 50
Assault: 50
Total videos: 200

**Download the official split files**

In [19]:
from huggingface_hub import hf_hub_download

repo_id = "jinmang2/ucf_crime"
split_folder = "UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/"

# downloading train split
train_split_path = hf_hub_download(
    repo_id=repo_id,
    filename=split_folder + "Anomaly_Train.txt",
    repo_type="dataset"
)
# downloading test splits
test_split_path = hf_hub_download(
    repo_id=repo_id,
    filename=split_folder + "Anomaly_Test.txt",
    repo_type="dataset"
)

print("Training split:", train_split_path)
print("Testing split:", test_split_path)

Training split: /root/.cache/huggingface/hub/datasets--jinmang2--ucf_crime/snapshots/6ea2a8930c6d625539b74804aa6e895c3c9d7dc5/UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/Anomaly_Train.txt
Testing split: /root/.cache/huggingface/hub/datasets--jinmang2--ucf_crime/snapshots/6ea2a8930c6d625539b74804aa6e895c3c9d7dc5/UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/Anomaly_Test.txt

**Identify training and testing videos**

In [20]:

with open(train_split_path, "r") as f:
    train_lines = [line.strip() for line in f if line.strip()]

with open(test_split_path, "r") as f:
    test_lines = [line.strip() for line in f if line.strip()]


train_names = {line.split("/")[-1].replace("\\", "/") for line in train_lines}
test_names = {line.split("/")[-1].replace("\\", "/") for line in test_lines}


train_videos = []
test_videos = []
unmatched_videos = []

for video in extracted_videos:
    video_name = os.path.basename(video)

    if video_name in train_names:
        train_videos.append(video)
    elif video_name in test_names:
        test_videos.append(video)
    else:
        unmatched_videos.append(video)


print("Training videos:", len(train_videos))
print("Testing videos:", len(test_videos))
print("Unmatched videos:", len(unmatched_videos))

Training videos: 181
Testing videos: 19
Unmatched videos: 0

**Creating dataframe to store metadata of part 1 video file**

In [21]:
import pandas as pd
import os

video_records = []

for video in train_videos:
    video_records.append({
        "video_path": video,
        "video_name": os.path.basename(video),
        "category": os.path.basename(os.path.dirname(video)),
        "split": "train",
        "label": 1
    })

for video in test_videos:
    video_records.append({
        "video_path": video,
        "video_name": os.path.basename(video),
        "category": os.path.basename(os.path.dirname(video)),
        "split": "test",
        "label": 1
    })

part1_df = pd.DataFrame(video_records)

print("Metadata shape:", part1_df.shape)
display(part1_df.head())

Metadata shape: (200, 5)

,video_path,video_name,category,split,label
0,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault030_x264.mp4,Assault,train,1
1,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault034_x264.mp4,Assault,train,1
2,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault004_x264.mp4,Assault,train,1
3,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault041_x264.mp4,Assault,train,1
4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault038_x264.mp4,Assault,train,1

**Prepare Pre-Trained ResNet50 to extract information from frames**

In [22]:
import torch
from torchvision import models, transforms


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


weights = models.ResNet50_Weights.DEFAULT
model = models.resnet50(weights=weights)

# Removing the final classification layer
model = torch.nn.Sequential(*list(model.children())[:-1])

# Set the model to evaluation mode, becoz model is already trained
model = model.to(device)
model.eval()

# Image preprocessing required by the pretrained weights,
## these weights handles the required operations, including resizing, cropping, converting the image to a tensor, and normalising its values.
preprocess = weights.transforms()

print("ResNet50 is ready.")
print("Device:", device)

Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 169MB/s]

ResNet50 is ready.
Device: cpu

**Testing ResNet50 to extract information from a video's frame**

In [23]:
import cv2
import numpy as np
import torch
from PIL import Image

# select the first video from traing set
video_path = train_videos[0]

# open the slecetd video
cap = cv2.VideoCapture(video_path)

# Read the first frame of the sopend video
success, frame = cap.read()
cap.release()

if success:
    # Convert OpenCV BGR image to RGB, bcoz OpenCV read images in BGR order
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    image = Image.fromarray(frame)

    # Apply ResNet50 preprocessing
    image_tensor = preprocess(image).unsqueeze(0).to(device)

    # Extract features
    with torch.no_grad():
        features = model(image_tensor)

    # Convert features to a NumPy array
    features = features.squeeze().cpu().numpy()

    print("Video:", video_path)
    print("Feature shape:", features.shape)
    print("Feature data type:", features.dtype)
else:
    print("Could not read the video frame.")

Video: /content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault030_x264.mp4
Feature shape: (2048,)
Feature data type: float32

**Extracting features from 16 selected frames of one video.**

In [24]:
import cv2
import numpy as np
import torch
from PIL import Image

video_path = train_videos[0]
num_frames = 16

cap = cv2.VideoCapture(video_path)
# get total frames of the video
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

if total_frames > 0:
    # Select 16 frames acrosss the video
    frame_indices = np.linspace(
        0, total_frames - 1, num_frames, dtype=int
    )

    video_features = []
#process each frames
    for frame_index in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
        success, frame = cap.read()

        if not success:
            continue

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(frame)
        image_tensor = preprocess(image).unsqueeze(0).to(device)

        with torch.no_grad():
            features = model(image_tensor)

        features = features.squeeze().cpu().numpy()
        video_features.append(features)

cap.release()

video_features = np.array(video_features, dtype=np.float32)

print("Video:", video_path)
print("Total frames in video:", total_frames)
print("Frames successfully processed:", len(video_features))
print("Feature shape:", video_features.shape)

Video: /content/UCF_Crime/videos/Anomaly-Videos-Part-1/Assault/Assault030_x264.mp4
Total frames in video: 1767
Frames successfully processed: 16
Feature shape: (16, 2048)

**Save the extracted features in Google Drive (Selected video's frame)**

In [25]:
import os
import numpy as np

# Create a folder for the test features
save_folder = "/content/drive/MyDrive/UCF_Crime_Project/features/train/Assault"
os.makedirs(save_folder, exist_ok=True)

# Save the features using the original video filename
feature_name = os.path.splitext(os.path.basename(video_path))[0] + ".npy"
feature_path = os.path.join(save_folder, feature_name)

np.save(feature_path, video_features)

print("Features saved to:", feature_path)
print("File exists:", os.path.exists(feature_path))

Features saved to: /content/drive/MyDrive/UCF_Crime_Project/features/train/Assault/Assault030_x264.npy
File exists: True

**Load the saved features and verify them**

In [26]:
saved_features = np.load(feature_path)

print("Loaded feature shape:", saved_features.shape)
print("Data type:", saved_features.dtype)
print("All values are finite:", np.isfinite(saved_features).all())

Loaded feature shape: (16, 2048)
Data type: float32
All values are finite: True

**Create a metadata table for Part 1**

In [27]:
import os
import pandas as pd

video_records = []

for video in extracted_videos:
    video_name = os.path.basename(video)
    category = os.path.basename(os.path.dirname(video))

    if video in train_videos:
        split = "train"
    elif video in test_videos:
        split = "test"
    else:
        split = "unknown"

    video_records.append({
        "video_name": video_name,
        "video_path": video,
        "category": category,
        "split": split
    })

video_df = pd.DataFrame(video_records)

print("Total videos:", len(video_df))
print("\nVideos by split:")
print(video_df["split"].value_counts())

print("\nVideos by category and split:")
print(pd.crosstab(video_df["category"], video_df["split"]))

video_df.head()

Total videos: 200

Videos by split:
split
train    181
test      19
Name: count, dtype: int64

Videos by category and split:
split     test  train
category
Abuse        2     48
Arrest       5     45
Arson        9     41
Assault      3     47

,video_name,video_path,category,split
0,Assault030_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train
1,Assault034_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train
2,Assault004_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train
3,Assault041_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train
4,Assault011_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,test

**Check the category names**

In [28]:
print("Categories in Part 1:")
print(sorted(video_df["category"].unique()))

Categories in Part 1:
['Abuse', 'Arrest', 'Arson', 'Assault']

**Add labels and save the metadata**

In [29]:
# based on previous cell output all videos in Part 1 belong to anomaly categories
video_df["label"] = 1

# Save the metadata in Google Drive
metadata_path = (
    "/content/drive/MyDrive/UCF_Crime_Project/"
    "metadata/part1_metadata.csv"
)

video_df.to_csv(metadata_path, index=False)

print("Metadata saved successfully.")
print("File location:", metadata_path)

print("\nLabel counts:")
print(video_df["label"].value_counts())

video_df.head()

Metadata saved successfully.
File location: /content/drive/MyDrive/UCF_Crime_Project/metadata/part1_metadata.csv

Label counts:
label
1    200
Name: count, dtype: int64

,video_name,video_path,category,split,label
0,Assault030_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train,1
1,Assault034_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train,1
2,Assault004_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train,1
3,Assault041_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train,1
4,Assault011_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,test,1

**Extract and save features for five videos for testing purpose**

In [30]:
import os
import numpy as np
import cv2
import torch
from PIL import Image

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"

num_frames = 16
results = []

# Test with the first five videos
for _, row in video_df.head(5).iterrows():

    video_path = row["video_path"]
    video_name = row["video_name"]
    category = row["category"]
    split = row["split"]

    # Create the correct folder automatically
    save_folder = os.path.join(feature_root, split, category)
    os.makedirs(save_folder, exist_ok=True)

    # Create the output filename
    feature_name = os.path.splitext(video_name)[0] + ".npy"
    feature_path = os.path.join(save_folder, feature_name)

    # Skip files that have already been saved correctly
    if os.path.exists(feature_path):
        saved_features = np.load(feature_path)

        if saved_features.shape == (num_frames, 2048):
            print("Already saved:", video_name)
            results.append({
                "video_name": video_name,
                "status": "Already saved"
            })
            continue

    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total_frames < num_frames:
        cap.release()
        print("Not enough frames:", video_name)
        results.append({
            "video_name": video_name,
            "status": "Failed: not enough frames"
        })
        continue

    frame_indices = np.linspace(
        0, total_frames - 1, num_frames, dtype=int
    )

    features_list = []

    for frame_index in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
        success, frame = cap.read()

        if not success:
            break

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(frame)
        image_tensor = preprocess(image).unsqueeze(0).to(device)

        with torch.no_grad():
            features = model(image_tensor)

        features = features.squeeze().cpu().numpy()
        features_list.append(features)

    cap.release()

    if len(features_list) == num_frames:
        video_features = np.array(features_list, dtype=np.float32)
        np.save(feature_path, video_features)

        print("Saved:", video_name, video_features.shape)

        results.append({
            "video_name": video_name,
            "status": "Success"
        })

    else:
        print("Failed to process:", video_name)

        results.append({
            "video_name": video_name,
            "status": "Failed: frame reading"
        })

print("\nTest batch finished.")

Already saved: Assault030_x264.mp4
Already saved: Assault034_x264.mp4
Already saved: Assault004_x264.mp4
Already saved: Assault041_x264.mp4
Already saved: Assault011_x264.mp4

Test batch finished.

**Process all 200 videos in Part 1**

In [31]:

import os
import cv2
import numpy as np
import pandas as pd
import torch
from PIL import Image

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"
log_path = "/content/drive/MyDrive/UCF_Crime_Project/metadata/part1_processing_log.csv"

num_frames = 16
results = []

total_videos = len(video_df)

for index, row in video_df.iterrows():

    video_path = row["video_path"]
    video_name = row["video_name"]
    category = row["category"]
    split = row["split"]

    save_folder = os.path.join(feature_root, split, category)
    os.makedirs(save_folder, exist_ok=True)

    feature_name = os.path.splitext(video_name)[0] + ".npy"
    feature_path = os.path.join(save_folder, feature_name)

    # Skip a video if its saved features are valid
    if os.path.exists(feature_path):
        try:
            saved_features = np.load(feature_path)

            if (saved_features.shape == (num_frames, 2048)
                    and np.isfinite(saved_features).all()):

                results.append({
                    "video_name": video_name,
                    "category": category,
                    "split": split,
                    "status": "Success"
                })

                print(f"[{index + 1}/{total_videos}] Already saved: {video_name}")
                continue

        except Exception:
            pass

    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if not cap.isOpened() or total_frames < num_frames:
        cap.release()

        results.append({
            "video_name": video_name,
            "category": category,
            "split": split,
            "status": "Failed: video unavailable or too short"
        })

        print(f"[{index + 1}/{total_videos}] Failed: {video_name}")
        continue

    frame_indices = np.linspace(
        0, total_frames - 1, num_frames, dtype=int
    )

    features_list = []

    for frame_index in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
        success, frame = cap.read()

        if not success:
            break

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(frame)
        image_tensor = preprocess(image).unsqueeze(0).to(device)

        with torch.no_grad():
            features = model(image_tensor)

        features = features.squeeze().cpu().numpy()
        features_list.append(features)

    cap.release()

    if len(features_list) == num_frames:
        video_features = np.array(features_list, dtype=np.float32)

        if np.isfinite(video_features).all():
            np.save(feature_path, video_features)

            status = "Success"
            print(
                f"[{index + 1}/{total_videos}] "
                f"Saved: {video_name} {video_features.shape}"
            )
        else:
            status = "Failed: invalid feature values"
            print(f"[{index + 1}/{total_videos}] Failed: {video_name}")
    else:
        status = "Failed: frame reading"
        print(f"[{index + 1}/{total_videos}] Failed: {video_name}")

    results.append({
        "video_name": video_name,
        "category": category,
        "split": split,
        "status": status
    })

    # Save the log after every video
    pd.DataFrame(results).to_csv(log_path, index=False)

print("\nPart 1 feature extraction finished.")
print(pd.DataFrame(results)["status"].value_counts())
print("Processing log:", log_path)

[1/200] Already saved: Assault030_x264.mp4
[2/200] Already saved: Assault034_x264.mp4
[3/200] Already saved: Assault004_x264.mp4
[4/200] Already saved: Assault041_x264.mp4
[5/200] Already saved: Assault011_x264.mp4
[6/200] Already saved: Assault038_x264.mp4
[7/200] Already saved: Assault040_x264.mp4
[8/200] Already saved: Assault023_x264.mp4
[9/200] Already saved: Assault013_x264.mp4
[10/200] Already saved: Assault019_x264.mp4
[11/200] Already saved: Assault017_x264.mp4
[12/200] Already saved: Assault027_x264.mp4
[13/200] Already saved: Assault046_x264.mp4
[14/200] Already saved: Assault010_x264.mp4
[15/200] Already saved: Assault033_x264.mp4
[16/200] Already saved: Assault029_x264.mp4
[17/200] Already saved: Assault009_x264.mp4
[18/200] Already saved: Assault014_x264.mp4
[19/200] Already saved: Assault003_x264.mp4
[20/200] Already saved: Assault035_x264.mp4
[21/200] Already saved: Assault037_x264.mp4
[22/200] Already saved: Assault020_x264.mp4
[23/200] Already saved: Assault016_x264.mp4
[24/200] Already saved: Assault044_x264.mp4
[25/200] Already saved: Assault026_x264.mp4
[26/200] Already saved: Assault022_x264.mp4
[27/200] Already saved: Assault052_x264.mp4
[28/200] Already saved: Assault049_x264.mp4
[29/200] Already saved: Assault024_x264.mp4
[30/200] Already saved: Assault050_x264.mp4
[31/200] Already saved: Assault007_x264.mp4
[32/200] Already saved: Assault051_x264.mp4
[33/200] Already saved: Assault005_x264.mp4
[34/200] Already saved: Assault025_x264.mp4
[35/200] Already saved: Assault006_x264.mp4
[36/200] Already saved: Assault045_x264.mp4
[37/200] Already saved: Assault036_x264.mp4
[38/200] Already saved: Assault028_x264.mp4
[39/200] Already saved: Assault008_x264.mp4
[40/200] Already saved: Assault032_x264.mp4
[41/200] Already saved: Assault012_x264.mp4
[42/200] Already saved: Assault015_x264.mp4
[43/200] Already saved: Assault031_x264.mp4
[44/200] Already saved: Assault002_x264.mp4
[45/200] Already saved: Assault018_x264.mp4
[46/200] Already saved: Assault039_x264.mp4
[47/200] Already saved: Assault047_x264.mp4
[48/200] Already saved: Assault042_x264.mp4
[49/200] Already saved: Assault048_x264.mp4
[50/200] Already saved: Assault001_x264.mp4
[51/200] Already saved: Abuse049_x264.mp4
[52/200] Already saved: Abuse002_x264.mp4
[53/200] Already saved: Abuse020_x264.mp4
[54/200] Already saved: Abuse050_x264.mp4
[55/200] Already saved: Abuse041_x264.mp4
[56/200] Already saved: Abuse028_x264.mp4
[57/200] Already saved: Abuse047_x264.mp4
[58/200] Already saved: Abuse042_x264.mp4
[59/200] Already saved: Abuse024_x264.mp4
[60/200] Already saved: Abuse036_x264.mp4
[61/200] Already saved: Abuse046_x264.mp4
[62/200] Already saved: Abuse030_x264.mp4
[63/200] Already saved: Abuse045_x264.mp4
[64/200] Already saved: Abuse009_x264.mp4
[65/200] Already saved: Abuse043_x264.mp4
[66/200] Already saved: Abuse032_x264.mp4
[67/200] Already saved: Abuse014_x264.mp4
[68/200] Already saved: Abuse010_x264.mp4
[69/200] Already saved: Abuse017_x264.mp4
[70/200] Already saved: Abuse001_x264.mp4
[71/200] Already saved: Abuse019_x264.mp4
[72/200] Already saved: Abuse005_x264.mp4
[73/200] Already saved: Abuse003_x264.mp4
[74/200] Already saved: Abuse007_x264.mp4
[75/200] Already saved: Abuse008_x264.mp4
[76/200] Already saved: Abuse044_x264.mp4
[77/200] Already saved: Abuse033_x264.mp4
[78/200] Already saved: Abuse011_x264.mp4
[79/200] Already saved: Abuse023_x264.mp4
[80/200] Already saved: Abuse040_x264.mp4
[81/200] Already saved: Abuse021_x264.mp4
[82/200] Already saved: Abuse006_x264.mp4
[83/200] Already saved: Abuse025_x264.mp4
[84/200] Already saved: Abuse015_x264.mp4
[85/200] Already saved: Abuse012_x264.mp4
[86/200] Already saved: Abuse016_x264.mp4
[87/200] Already saved: Abuse022_x264.mp4
[88/200] Already saved: Abuse026_x264.mp4
[89/200] Already saved: Abuse004_x264.mp4
[90/200] Already saved: Abuse039_x264.mp4
[91/200] Already saved: Abuse048_x264.mp4
[92/200] Already saved: Abuse018_x264.mp4
[93/200] Already saved: Abuse037_x264.mp4
[94/200] Already saved: Abuse035_x264.mp4
[95/200] Already saved: Abuse034_x264.mp4
[96/200] Already saved: Abuse027_x264.mp4
[97/200] Already saved: Abuse013_x264.mp4
[98/200] Already saved: Abuse029_x264.mp4
[99/200] Already saved: Abuse038_x264.mp4
[100/200] Already saved: Abuse031_x264.mp4
[101/200] Already saved: Arrest022_x264.mp4
[102/200] Already saved: Arrest005_x264.mp4
[103/200] Already saved: Arrest041_x264.mp4
[104/200] Already saved: Arrest010_x264.mp4
[105/200] Already saved: Arrest042_x264.mp4
[106/200] Already saved: Arrest008_x264.mp4
[107/200] Already saved: Arrest046_x264.mp4
[108/200] Already saved: Arrest028_x264.mp4
[109/200] Already saved: Arrest048_x264.mp4
[110/200] Already saved: Arrest036_x264.mp4
[111/200] Already saved: Arrest027_x264.mp4
[112/200] Already saved: Arrest047_x264.mp4
[113/200] Already saved: Arrest029_x264.mp4
[114/200] Already saved: Arrest031_x264.mp4
[115/200] Already saved: Arrest006_x264.mp4
[116/200] Already saved: Arrest049_x264.mp4
[117/200] Already saved: Arrest003_x264.mp4
[118/200] Already saved: Arrest038_x264.mp4
[119/200] Already saved: Arrest034_x264.mp4
[120/200] Already saved: Arrest024_x264.mp4
[121/200] Already saved: Arrest017_x264.mp4
[122/200] Already saved: Arrest023_x264.mp4
[123/200] Already saved: Arrest051_x264.mp4
[124/200] Already saved: Arrest009_x264.mp4
[125/200] Already saved: Arrest035_x264.mp4
[126/200] Already saved: Arrest021_x264.mp4
[127/200] Already saved: Arrest050_x264.mp4
[128/200] Already saved: Arrest037_x264.mp4
[129/200] Already saved: Arrest018_x264.mp4
[130/200] Already saved: Arrest001_x264.mp4
[131/200] Already saved: Arrest044_x264.mp4
[132/200] Already saved: Arrest016_x264.mp4
[133/200] Already saved: Arrest014_x264.mp4
[134/200] Already saved: Arrest030_x264.mp4
[135/200] Already saved: Arrest025_x264.mp4
[136/200] Already saved: Arrest002_x264.mp4
[137/200] Already saved: Arrest039_x264.mp4
[138/200] Already saved: Arrest040_x264.mp4
[139/200] Already saved: Arrest011_x264.mp4
[140/200] Already saved: Arrest015_x264.mp4
[141/200] Already saved: Arrest019_x264.mp4
[142/200] Already saved: Arrest033_x264.mp4
[143/200] Already saved: Arrest043_x264.mp4
[144/200] Already saved: Arrest026_x264.mp4
[145/200] Already saved: Arrest004_x264.mp4
[146/200] Already saved: Arrest013_x264.mp4
[147/200] Already saved: Arrest032_x264.mp4
[148/200] Already saved: Arrest007_x264.mp4
[149/200] Already saved: Arrest020_x264.mp4
[150/200] Already saved: Arrest012_x264.mp4
[151/200] Already saved: Arson027_x264.mp4
[152/200] Already saved: Arson020_x264.mp4
[153/200] Already saved: Arson022_x264.mp4
[154/200] Already saved: Arson014_x264.mp4
[155/200] Already saved: Arson040_x264.mp4
[156/200] Already saved: Arson048_x264.mp4
[157/200] Already saved: Arson028_x264.mp4
[158/200] Already saved: Arson008_x264.mp4
[159/200] Already saved: Arson034_x264.mp4
[160/200] Already saved: Arson024_x264.mp4
[161/200] Already saved: Arson012_x264.mp4
[162/200] Already saved: Arson050_x264.mp4
[163/200] Already saved: Arson018_x264.mp4
[164/200] Already saved: Arson045_x264.mp4
[165/200] Already saved: Arson051_x264.mp4
[166/200] Already saved: Arson001_x264.mp4
[167/200] Already saved: Arson021_x264.mp4
[168/200] Already saved: Arson013_x264.mp4
[169/200] Already saved: Arson005_x264.mp4
[170/200] Already saved: Arson010_x264.mp4
[171/200] Already saved: Arson041_x264.mp4
[172/200] Already saved: Arson053_x264.mp4
[173/200] Already saved: Arson025_x264.mp4
[174/200] Already saved: Arson031_x264.mp4
[175/200] Already saved: Arson011_x264.mp4
[176/200] Already saved: Arson030_x264.mp4
[177/200] Already saved: Arson016_x264.mp4
[178/200] Already saved: Arson019_x264.mp4
[179/200] Already saved: Arson049_x264.mp4
[180/200] Already saved: Arson029_x264.mp4
[181/200] Already saved: Arson015_x264.mp4
[182/200] Already saved: Arson003_x264.mp4
[183/200] Already saved: Arson017_x264.mp4
[184/200] Already saved: Arson002_x264.mp4
[185/200] Already saved: Arson038_x264.mp4
[186/200] Already saved: Arson009_x264.mp4
[187/200] Already saved: Arson046_x264.mp4
[188/200] Already saved: Arson032_x264.mp4
[189/200] Already saved: Arson035_x264.mp4
[190/200] Already saved: Arson007_x264.mp4
[191/200] Already saved: Arson026_x264.mp4
[192/200] Already saved: Arson047_x264.mp4
[193/200] Already saved: Arson039_x264.mp4
[194/200] Already saved: Arson044_x264.mp4
[195/200] Already saved: Arson042_x264.mp4
[196/200] Already saved: Arson052_x264.mp4
[197/200] Already saved: Arson036_x264.mp4
[198/200] Already saved: Arson006_x264.mp4
[199/200] Already saved: Arson037_x264.mp4
[200/200] Already saved: Arson023_x264.mp4

Part 1 feature extraction finished.
status
Success    200
Name: count, dtype: int64
Processing log: /content/drive/MyDrive/UCF_Crime_Project/metadata/part1_processing_log.csv

**verify the saved files**

In [32]:

import os
import numpy as np
from collections import Counter

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"

feature_counts = Counter()
invalid_files = []

for split in ["train", "test"]:
    split_folder = os.path.join(feature_root, split)

    for category in os.listdir(split_folder):
        category_folder = os.path.join(split_folder, category)

        if not os.path.isdir(category_folder):
            continue

        for file_name in os.listdir(category_folder):
            if file_name.endswith(".npy"):
                feature_counts[split] += 1

                file_path = os.path.join(category_folder, file_name)
                features = np.load(file_path)

                if (features.shape != (16, 2048)
                        or not np.isfinite(features).all()):
                    invalid_files.append(file_path)

print("Training feature files:", feature_counts["train"])
print("Testing feature files:", feature_counts["test"])
print("Total feature files:", sum(feature_counts.values()))
print("Invalid feature files:", len(invalid_files))

Training feature files: 182
Testing feature files: 19
Total feature files: 201
Invalid feature files: 0

**For Part 2**

**Download Part 2**

In [33]:

from huggingface_hub import hf_hub_download
import os

repo_id = "jinmang2/ucf_crime"
file_name = "Anomaly-Videos-Part-2.zip"

zip_path = hf_hub_download(
    repo_id=repo_id,
    filename=file_name,
    repo_type="dataset",
    local_dir="/content/UCF_Crime"
)

print("Download completed:", os.path.exists(zip_path))
print("ZIP path:", zip_path)
print("File size (GB):", round(os.path.getsize(zip_path) / (1024**3), 2))

Download completed: True
ZIP path: /content/UCF_Crime/Anomaly-Videos-Part-2.zip
File size (GB): 6.23

**Extract the part 2 videos **

In [34]:

import os
import zipfile

extract_path = "/content/UCF_Crime/videos"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

part2_folder = os.path.join(
    extract_path,
    "Anomaly-Videos-Part-2"
)

video_files = []

for root, dirs, files in os.walk(part2_folder):
    for file in files:
        if file.lower().endswith(".mp4"):
            video_files.append(os.path.join(root, file))

print("Part 2 folder exists:", os.path.exists(part2_folder))
print("Total extracted videos:", len(video_files))

print("\nFirst five videos:")
for video in video_files[:5]:
    print(video)

Part 2 folder exists: True
Total extracted videos: 200

First five videos:
/content/UCF_Crime/videos/Anomaly-Videos-Part-2/Fighting/Fighting025_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-2/Fighting/Fighting050_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-2/Fighting/Fighting030_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-2/Fighting/Fighting002_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-2/Fighting/Fighting022_x264.mp4

In [35]:

import os
import pandas as pd

# Get video filenames from the official split lists
train_names = {
    line.strip().replace("\\", "/").split("/")[-1]
    for line in train_lines
    if line.strip()
}

test_names = {
    line.strip().replace("\\", "/").split("/")[-1]
    for line in test_lines
    if line.strip()
}

video_records = []

for video_path in video_files:
    video_name = os.path.basename(video_path)
    category = os.path.basename(os.path.dirname(video_path))

    if video_name in train_names:
        split = "train"
    elif video_name in test_names:
        split = "test"
    else:
        split = "unknown"

    video_records.append({
        "video_path": video_path,
        "video_name": video_name,
        "category": category,
        "split": split,
        "label": 1
    })

part2_df = pd.DataFrame(video_records)

print("Metadata shape:", part2_df.shape)

print("\nSplit counts:")
print(part2_df["split"].value_counts())

print("\nCategory and split counts:")
print(pd.crosstab(part2_df["category"], part2_df["split"]))

print("\nUnmatched videos:",
      (part2_df["split"] == "unknown").sum())

display(part2_df.head())

Metadata shape: (200, 5)

Split counts:
split
train    161
test      39
Name: count, dtype: int64

Category and split counts:
split      test  train
category
Burglary     13     87
Explosion    21     29
Fighting      5     45

Unmatched videos: 0

,video_path,video_name,category,split,label
0,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Fighting025_x264.mp4,Fighting,train,1
1,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Fighting050_x264.mp4,Fighting,train,1
2,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Fighting030_x264.mp4,Fighting,train,1
3,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Fighting002_x264.mp4,Fighting,train,1
4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Fighting022_x264.mp4,Fighting,train,1

**Extract ResNet50 features for Part 2**

In [36]:

import os
import cv2
import numpy as np
import pandas as pd
import torch
from PIL import Image

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"

log_path = (
    "/content/drive/MyDrive/UCF_Crime_Project/"
    "metadata/part2_processing_log.csv"
)

metadata_path = (
    "/content/drive/MyDrive/UCF_Crime_Project/"
    "metadata/part2_metadata.csv"
)

num_frames = 16
results = []

# Save Part 2 metadata
part2_df.to_csv(metadata_path, index=False)

for index, row in part2_df.iterrows():

    video_path = row["video_path"]
    video_name = row["video_name"]
    category = row["category"]
    split = row["split"]

    save_folder = os.path.join(
        feature_root, split, category
    )
    os.makedirs(save_folder, exist_ok=True)

    feature_name = os.path.splitext(video_name)[0] + ".npy"
    feature_path = os.path.join(save_folder, feature_name)

    # Skip already saved valid features
    if os.path.exists(feature_path):
        try:
            saved_features = np.load(feature_path)

            if (saved_features.shape == (16, 2048)
                    and np.isfinite(saved_features).all()):

                status = "Success"
                print(
                    f"[{index + 1}/200] Already saved: "
                    f"{video_name}"
                )

                results.append({
                    "video_name": video_name,
                    "category": category,
                    "split": split,
                    "status": status
                })

                pd.DataFrame(results).to_csv(
                    log_path, index=False
                )
                continue

        except Exception:
            pass

    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    features_list = []

    if cap.isOpened() and total_frames >= num_frames:

        frame_indices = np.linspace(
            0, total_frames - 1, num_frames, dtype=int
        )

        for frame_index in frame_indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
            success, frame = cap.read()

            if not success:
                break

            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image = Image.fromarray(frame)
            image_tensor = preprocess(image).unsqueeze(0).to(device)

            with torch.no_grad():
                features = model(image_tensor)

            features = features.squeeze().cpu().numpy()
            features_list.append(features)

    cap.release()

    if len(features_list) == num_frames:
        video_features = np.array(features_list, dtype=np.float32)

        if np.isfinite(video_features).all():
            np.save(feature_path, video_features)
            status = "Success"
            print(
                f"[{index + 1}/200] Saved: "
                f"{video_name} {video_features.shape}"
            )
        else:
            status = "Failed: invalid feature values"
            print(f"[{index + 1}/200] Failed: {video_name}")
    else:
        status = "Failed: frame reading"
        print(f"[{index + 1}/200] Failed: {video_name}")

    results.append({
        "video_name": video_name,
        "category": category,
        "split": split,
        "status": status
    })

    # Save progress after every video
    pd.DataFrame(results).to_csv(log_path, index=False)

print("\nPart 2 feature extraction finished.")
print(pd.DataFrame(results)["status"].value_counts())
print("Processing log:", log_path)

[1/200] Saved: Fighting025_x264.mp4 (16, 2048)
[2/200] Saved: Fighting050_x264.mp4 (16, 2048)
[3/200] Saved: Fighting030_x264.mp4 (16, 2048)
[4/200] Saved: Fighting002_x264.mp4 (16, 2048)
[5/200] Saved: Fighting022_x264.mp4 (16, 2048)
[6/200] Saved: Fighting048_x264.mp4 (16, 2048)
[7/200] Saved: Fighting043_x264.mp4 (16, 2048)
[8/200] Saved: Fighting006_x264.mp4 (16, 2048)
[9/200] Saved: Fighting039_x264.mp4 (16, 2048)
[10/200] Saved: Fighting037_x264.mp4 (16, 2048)
[11/200] Saved: Fighting040_x264.mp4 (16, 2048)
[12/200] Saved: Fighting015_x264.mp4 (16, 2048)
[13/200] Saved: Fighting017_x264.mp4 (16, 2048)
[14/200] Saved: Fighting004_x264.mp4 (16, 2048)
[15/200] Saved: Fighting047_x264.mp4 (16, 2048)
[16/200] Saved: Fighting026_x264.mp4 (16, 2048)
[17/200] Saved: Fighting028_x264.mp4 (16, 2048)
[18/200] Saved: Fighting013_x264.mp4 (16, 2048)
[19/200] Saved: Fighting024_x264.mp4 (16, 2048)
[20/200] Saved: Fighting038_x264.mp4 (16, 2048)
[21/200] Saved: Fighting011_x264.mp4 (16, 2048)
[22/200] Saved: Fighting042_x264.mp4 (16, 2048)
[23/200] Saved: Fighting041_x264.mp4 (16, 2048)
[24/200] Saved: Fighting033_x264.mp4 (16, 2048)
[25/200] Saved: Fighting005_x264.mp4 (16, 2048)
[26/200] Saved: Fighting032_x264.mp4 (16, 2048)
[27/200] Saved: Fighting035_x264.mp4 (16, 2048)
[28/200] Saved: Fighting012_x264.mp4 (16, 2048)
[29/200] Saved: Fighting031_x264.mp4 (16, 2048)
[30/200] Saved: Fighting034_x264.mp4 (16, 2048)
[31/200] Saved: Fighting008_x264.mp4 (16, 2048)
[32/200] Saved: Fighting016_x264.mp4 (16, 2048)
[33/200] Saved: Fighting051_x264.mp4 (16, 2048)
[34/200] Saved: Fighting044_x264.mp4 (16, 2048)
[35/200] Saved: Fighting036_x264.mp4 (16, 2048)
[36/200] Saved: Fighting046_x264.mp4 (16, 2048)
[37/200] Saved: Fighting045_x264.mp4 (16, 2048)
[38/200] Saved: Fighting029_x264.mp4 (16, 2048)
[39/200] Saved: Fighting010_x264.mp4 (16, 2048)
[40/200] Saved: Fighting021_x264.mp4 (16, 2048)
[41/200] Saved: Fighting020_x264.mp4 (16, 2048)
[42/200] Saved: Fighting007_x264.mp4 (16, 2048)
[43/200] Saved: Fighting049_x264.mp4 (16, 2048)
[44/200] Saved: Fighting009_x264.mp4 (16, 2048)
[45/200] Saved: Fighting014_x264.mp4 (16, 2048)
[46/200] Saved: Fighting003_x264.mp4 (16, 2048)
[47/200] Saved: Fighting019_x264.mp4 (16, 2048)
[48/200] Saved: Fighting018_x264.mp4 (16, 2048)
[49/200] Saved: Fighting027_x264.mp4 (16, 2048)
[50/200] Saved: Fighting023_x264.mp4 (16, 2048)
[51/200] Saved: Burglary095_x264.mp4 (16, 2048)
[52/200] Saved: Burglary035_x264.mp4 (16, 2048)
[53/200] Saved: Burglary056_x264.mp4 (16, 2048)
[54/200] Saved: Burglary083_x264.mp4 (16, 2048)
[55/200] Saved: Burglary077_x264.mp4 (16, 2048)
[56/200] Saved: Burglary036_x264.mp4 (16, 2048)
[57/200] Saved: Burglary091_x264.mp4 (16, 2048)
[58/200] Saved: Burglary088_x264.mp4 (16, 2048)
[59/200] Saved: Burglary026_x264.mp4 (16, 2048)
[60/200] Saved: Burglary043_x264.mp4 (16, 2048)
[61/200] Saved: Burglary064_x264.mp4 (16, 2048)
[62/200] Saved: Burglary003_x264.mp4 (16, 2048)
[63/200] Saved: Burglary045_x264.mp4 (16, 2048)
[64/200] Saved: Burglary068_x264.mp4 (16, 2048)
[65/200] Saved: Burglary078_x264.mp4 (16, 2048)
[66/200] Saved: Burglary004_x264.mp4 (16, 2048)
[67/200] Saved: Burglary044_x264.mp4 (16, 2048)
[68/200] Saved: Burglary086_x264.mp4 (16, 2048)
[69/200] Saved: Burglary060_x264.mp4 (16, 2048)
[70/200] Saved: Burglary047_x264.mp4 (16, 2048)
[71/200] Saved: Burglary079_x264.mp4 (16, 2048)
[72/200] Saved: Burglary084_x264.mp4 (16, 2048)
[73/200] Saved: Burglary096_x264.mp4 (16, 2048)
[74/200] Saved: Burglary009_x264.mp4 (16, 2048)
[75/200] Saved: Burglary067_x264.mp4 (16, 2048)
[76/200] Saved: Burglary019_x264.mp4 (16, 2048)
[77/200] Saved: Burglary041_x264.mp4 (16, 2048)
[78/200] Saved: Burglary085_x264.mp4 (16, 2048)
[79/200] Saved: Burglary082_x264.mp4 (16, 2048)
[80/200] Saved: Burglary089_x264.mp4 (16, 2048)
[81/200] Saved: Burglary071_x264.mp4 (16, 2048)
[82/200] Saved: Burglary094_x264.mp4 (16, 2048)
[83/200] Saved: Burglary069_x264.mp4 (16, 2048)
[84/200] Saved: Burglary002_x264.mp4 (16, 2048)
[85/200] Saved: Burglary010_x264.mp4 (16, 2048)
[86/200] Saved: Burglary093_x264.mp4 (16, 2048)
[87/200] Saved: Burglary028_x264.mp4 (16, 2048)
[88/200] Saved: Burglary017_x264.mp4 (16, 2048)
[89/200] Saved: Burglary033_x264.mp4 (16, 2048)
[90/200] Saved: Burglary025_x264.mp4 (16, 2048)
[91/200] Saved: Burglary100_x264.mp4 (16, 2048)
[92/200] Saved: Burglary051_x264.mp4 (16, 2048)
[93/200] Saved: Burglary012_x264.mp4 (16, 2048)
[94/200] Saved: Burglary013_x264.mp4 (16, 2048)
[95/200] Saved: Burglary029_x264.mp4 (16, 2048)
[96/200] Saved: Burglary011_x264.mp4 (16, 2048)
[97/200] Saved: Burglary073_x264.mp4 (16, 2048)
[98/200] Saved: Burglary007_x264.mp4 (16, 2048)
[99/200] Saved: Burglary080_x264.mp4 (16, 2048)
[100/200] Saved: Burglary081_x264.mp4 (16, 2048)
[101/200] Saved: Burglary048_x264.mp4 (16, 2048)
[102/200] Saved: Burglary016_x264.mp4 (16, 2048)
[103/200] Saved: Burglary061_x264.mp4 (16, 2048)
[104/200] Saved: Burglary022_x264.mp4 (16, 2048)
[105/200] Saved: Burglary053_x264.mp4 (16, 2048)
[106/200] Saved: Burglary014_x264.mp4 (16, 2048)
[107/200] Saved: Burglary099_x264.mp4 (16, 2048)
[108/200] Saved: Burglary050_x264.mp4 (16, 2048)
[109/200] Saved: Burglary059_x264.mp4 (16, 2048)
[110/200] Saved: Burglary030_x264.mp4 (16, 2048)
[111/200] Saved: Burglary063_x264.mp4 (16, 2048)
[112/200] Saved: Burglary066_x264.mp4 (16, 2048)
[113/200] Saved: Burglary038_x264.mp4 (16, 2048)
[114/200] Saved: Burglary074_x264.mp4 (16, 2048)
[115/200] Saved: Burglary023_x264.mp4 (16, 2048)
[116/200] Saved: Burglary090_x264.mp4 (16, 2048)
[117/200] Saved: Burglary049_x264.mp4 (16, 2048)
[118/200] Saved: Burglary037_x264.mp4 (16, 2048)
[119/200] Saved: Burglary072_x264.mp4 (16, 2048)
[120/200] Saved: Burglary020_x264.mp4 (16, 2048)
[121/200] Saved: Burglary046_x264.mp4 (16, 2048)
[122/200] Saved: Burglary075_x264.mp4 (16, 2048)
[123/200] Saved: Burglary005_x264.mp4 (16, 2048)
[124/200] Saved: Burglary040_x264.mp4 (16, 2048)
[125/200] Saved: Burglary031_x264.mp4 (16, 2048)
[126/200] Saved: Burglary070_x264.mp4 (16, 2048)
[127/200] Saved: Burglary001_x264.mp4 (16, 2048)
[128/200] Saved: Burglary042_x264.mp4 (16, 2048)
[129/200] Saved: Burglary057_x264.mp4 (16, 2048)
[130/200] Saved: Burglary055_x264.mp4 (16, 2048)
[131/200] Saved: Burglary006_x264.mp4 (16, 2048)
[132/200] Saved: Burglary098_x264.mp4 (16, 2048)
[133/200] Saved: Burglary058_x264.mp4 (16, 2048)
[134/200] Saved: Burglary015_x264.mp4 (16, 2048)
[135/200] Saved: Burglary032_x264.mp4 (16, 2048)
[136/200] Saved: Burglary034_x264.mp4 (16, 2048)
[137/200] Saved: Burglary008_x264.mp4 (16, 2048)
[138/200] Saved: Burglary092_x264.mp4 (16, 2048)
[139/200] Saved: Burglary087_x264.mp4 (16, 2048)
[140/200] Saved: Burglary097_x264.mp4 (16, 2048)
[141/200] Saved: Burglary054_x264.mp4 (16, 2048)
[142/200] Saved: Burglary052_x264.mp4 (16, 2048)
[143/200] Saved: Burglary076_x264.mp4 (16, 2048)
[144/200] Saved: Burglary065_x264.mp4 (16, 2048)
[145/200] Saved: Burglary062_x264.mp4 (16, 2048)
[146/200] Saved: Burglary018_x264.mp4 (16, 2048)
[147/200] Saved: Burglary021_x264.mp4 (16, 2048)
[148/200] Saved: Burglary027_x264.mp4 (16, 2048)
[149/200] Saved: Burglary039_x264.mp4 (16, 2048)
[150/200] Saved: Burglary024_x264.mp4 (16, 2048)
[151/200] Saved: Explosion021_x264.mp4 (16, 2048)
[152/200] Saved: Explosion003_x264.mp4 (16, 2048)
[153/200] Saved: Explosion014_x264.mp4 (16, 2048)
[154/200] Saved: Explosion045_x264.mp4 (16, 2048)
[155/200] Saved: Explosion039_x264.mp4 (16, 2048)
[156/200] Saved: Explosion047_x264.mp4 (16, 2048)
[157/200] Saved: Explosion033_x264.mp4 (16, 2048)
[158/200] Saved: Explosion015_x264.mp4 (16, 2048)
[159/200] Saved: Explosion024_x264.mp4 (16, 2048)
[160/200] Saved: Explosion051_x264.mp4 (16, 2048)
[161/200] Saved: Explosion012_x264.mp4 (16, 2048)
[162/200] Saved: Explosion043_x264.mp4 (16, 2048)
[163/200] Saved: Explosion040_x264.mp4 (16, 2048)
[164/200] Saved: Explosion010_x264.mp4 (16, 2048)
[165/200] Saved: Explosion052_x264.mp4 (16, 2048)
[166/200] Saved: Explosion042_x264.mp4 (16, 2048)
[167/200] Saved: Explosion035_x264.mp4 (16, 2048)
[168/200] Saved: Explosion011_x264.mp4 (16, 2048)
[169/200] Saved: Explosion009_x264.mp4 (16, 2048)
[170/200] Saved: Explosion016_x264.mp4 (16, 2048)
[171/200] Saved: Explosion026_x264.mp4 (16, 2048)
[172/200] Saved: Explosion046_x264.mp4 (16, 2048)
[173/200] Saved: Explosion041_x264.mp4 (16, 2048)
[174/200] Saved: Explosion017_x264.mp4 (16, 2048)
[175/200] Saved: Explosion018_x264.mp4 (16, 2048)
[176/200] Saved: Explosion025_x264.mp4 (16, 2048)
[177/200] Saved: Explosion036_x264.mp4 (16, 2048)
[178/200] Saved: Explosion032_x264.mp4 (16, 2048)
[179/200] Saved: Explosion013_x264.mp4 (16, 2048)
[180/200] Saved: Explosion027_x264.mp4 (16, 2048)
[181/200] Saved: Explosion048_x264.mp4 (16, 2048)
[182/200] Saved: Explosion028_x264.mp4 (16, 2048)
[183/200] Saved: Explosion019_x264.mp4 (16, 2048)
[184/200] Saved: Explosion034_x264.mp4 (16, 2048)
[185/200] Saved: Explosion022_x264.mp4 (16, 2048)
[186/200] Saved: Explosion007_x264.mp4 (16, 2048)
[187/200] Saved: Explosion006_x264.mp4 (16, 2048)
[188/200] Saved: Explosion038_x264.mp4 (16, 2048)
[189/200] Saved: Explosion044_x264.mp4 (16, 2048)
[190/200] Saved: Explosion005_x264.mp4 (16, 2048)
[191/200] Saved: Explosion050_x264.mp4 (16, 2048)
[192/200] Saved: Explosion029_x264.mp4 (16, 2048)
[193/200] Saved: Explosion023_x264.mp4 (16, 2048)
[194/200] Saved: Explosion020_x264.mp4 (16, 2048)
[195/200] Saved: Explosion004_x264.mp4 (16, 2048)
[196/200] Saved: Explosion008_x264.mp4 (16, 2048)
[197/200] Saved: Explosion030_x264.mp4 (16, 2048)
[198/200] Saved: Explosion037_x264.mp4 (16, 2048)
[199/200] Saved: Explosion002_x264.mp4 (16, 2048)
[200/200] Saved: Explosion001_x264.mp4 (16, 2048)

Part 2 feature extraction finished.
status
Success    200
Name: count, dtype: int64
Processing log: /content/drive/MyDrive/UCF_Crime_Project/metadata/part2_processing_log.csv

**Downlaod PArt 3**

In [37]:

from huggingface_hub import hf_hub_download
import os

repo_id = "jinmang2/ucf_crime"
file_name = "Anomaly-Videos-Part-3.zip"

zip_path = hf_hub_download(
    repo_id=repo_id,
    filename=file_name,
    repo_type="dataset",
    local_dir="/content/UCF_Crime"
)

print("Download completed:", os.path.exists(zip_path))
print("ZIP path:", zip_path)
print("File size (GB):", round(os.path.getsize(zip_path) / (1024**3), 2))

Anomaly-Videos-Part-3.zip: reconstructing file:   0%|          |  0.00B / 5.62GB

Anomaly-Videos-Part-3.zip: downloading bytes:           |  0.00B

Download completed: True
ZIP path: /content/UCF_Crime/Anomaly-Videos-Part-3.zip
File size (GB): 5.23

**Extract Part 3 videos**

In [38]:

import os
import zipfile

extract_path = "/content/UCF_Crime/videos"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

part3_folder = os.path.join(
    extract_path,
    "Anomaly-Videos-Part-3"
)

video_files = []

for root, dirs, files in os.walk(part3_folder):
    for file in files:
        if file.lower().endswith(".mp4"):
            video_files.append(os.path.join(root, file))

print("Part 3 folder exists:", os.path.exists(part3_folder))
print("Total extracted videos:", len(video_files))

print("\nFirst five videos:")
for video in video_files[:5]:
    print(video)

Part 3 folder exists: True
Total extracted videos: 350

First five videos:
/content/UCF_Crime/videos/Anomaly-Videos-Part-3/RoadAccidents/RoadAccidents107_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-3/RoadAccidents/RoadAccidents033_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-3/RoadAccidents/RoadAccidents092_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-3/RoadAccidents/RoadAccidents087_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-3/RoadAccidents/RoadAccidents056_x264.mp4

**Match videos with the official training and testing splits**

In [39]:

import os
import pandas as pd

train_names = {
    line.strip().replace("\\", "/").split("/")[-1]
    for line in train_lines
    if line.strip()
}

test_names = {
    line.strip().replace("\\", "/").split("/")[-1]
    for line in test_lines
    if line.strip()
}

video_records = []

for video_path in video_files:
    video_name = os.path.basename(video_path)
    category = os.path.basename(os.path.dirname(video_path))

    if video_name in train_names:
        split = "train"
    elif video_name in test_names:
        split = "test"
    else:
        split = "unknown"

    video_records.append({
        "video_path": video_path,
        "video_name": video_name,
        "category": category,
        "split": split,
        "label": 1
    })

part3_df = pd.DataFrame(video_records)

print("Metadata shape:", part3_df.shape)

print("\nSplit counts:")
print(part3_df["split"].value_counts())

print("\nCategory and split counts:")
print(pd.crosstab(part3_df["category"], part3_df["split"]))

print("\nUnmatched videos:",
      (part3_df["split"] == "unknown").sum())

display(part3_df.head())

Metadata shape: (350, 5)

Split counts:
split
train    299
test      51
Name: count, dtype: int64

Category and split counts:
split          test  train
category
RoadAccidents    23    127
Robbery           5    145
Shooting         23     27

Unmatched videos: 0

,video_path,video_name,category,split,label
0,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,RoadAccidents107_x264.mp4,RoadAccidents,train,1
1,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,RoadAccidents033_x264.mp4,RoadAccidents,train,1
2,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,RoadAccidents092_x264.mp4,RoadAccidents,train,1
3,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,RoadAccidents087_x264.mp4,RoadAccidents,train,1
4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,RoadAccidents056_x264.mp4,RoadAccidents,train,1

**Extract and save Part 3 features**

In [40]:

import os
import cv2
import numpy as np
import pandas as pd
import torch
from PIL import Image

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"

log_path = (
    "/content/drive/MyDrive/UCF_Crime_Project/"
    "metadata/part3_processing_log.csv"
)

metadata_path = (
    "/content/drive/MyDrive/UCF_Crime_Project/"
    "metadata/part3_metadata.csv"
)

num_frames = 16
results = []

part3_df.to_csv(metadata_path, index=False)

for index, row in part3_df.iterrows():

    video_path = row["video_path"]
    video_name = row["video_name"]
    category = row["category"]
    split = row["split"]

    save_folder = os.path.join(
        feature_root, split, category
    )
    os.makedirs(save_folder, exist_ok=True)

    feature_name = os.path.splitext(video_name)[0] + ".npy"
    feature_path = os.path.join(save_folder, feature_name)

    # Skip valid features already saved
    if os.path.exists(feature_path):
        try:
            saved_features = np.load(feature_path)

            if (saved_features.shape == (16, 2048)
                    and np.isfinite(saved_features).all()):

                status = "Success"
                print(
                    f"[{index + 1}/{len(part3_df)}] "
                    f"Already saved: {video_name}"
                )

                results.append({
                    "video_name": video_name,
                    "category": category,
                    "split": split,
                    "status": status
                })

                pd.DataFrame(results).to_csv(
                    log_path, index=False
                )
                continue

        except Exception:
            pass

    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    features_list = []

    if cap.isOpened() and total_frames >= num_frames:

        frame_indices = np.linspace(
            0, total_frames - 1, num_frames, dtype=int
        )

        for frame_index in frame_indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
            success, frame = cap.read()

            if not success:
                break

            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image = Image.fromarray(frame)
            image_tensor = preprocess(image).unsqueeze(0).to(device)

            with torch.no_grad():
                features = model(image_tensor)

            features = features.squeeze().cpu().numpy()
            features_list.append(features)

    cap.release()

    if len(features_list) == num_frames:
        video_features = np.array(
            features_list, dtype=np.float32
        )

        if np.isfinite(video_features).all():
            np.save(feature_path, video_features)
            status = "Success"
            print(
                f"[{index + 1}/{len(part3_df)}] "
                f"Saved: {video_name} {video_features.shape}"
            )
        else:
            status = "Failed: invalid feature values"
            print(f"Failed: {video_name}")
    else:
        status = "Failed: frame reading"
        print(f"Failed: {video_name}")

    results.append({
        "video_name": video_name,
        "category": category,
        "split": split,
        "status": status
    })

    # Save progress after each video
    pd.DataFrame(results).to_csv(log_path, index=False)

print("\nPart 3 feature extraction finished.")
print(pd.DataFrame(results)["status"].value_counts())
print("Metadata saved:", metadata_path)
print("Processing log saved:", log_path)

[1/350] Saved: RoadAccidents107_x264.mp4 (16, 2048)
[2/350] Saved: RoadAccidents033_x264.mp4 (16, 2048)
[3/350] Saved: RoadAccidents092_x264.mp4 (16, 2048)
[4/350] Saved: RoadAccidents087_x264.mp4 (16, 2048)
[5/350] Saved: RoadAccidents056_x264.mp4 (16, 2048)
[6/350] Saved: RoadAccidents129_x264.mp4 (16, 2048)
[7/350] Saved: RoadAccidents083_x264.mp4 (16, 2048)
[8/350] Saved: RoadAccidents057_x264.mp4 (16, 2048)
[9/350] Saved: RoadAccidents125_x264.mp4 (16, 2048)
[10/350] Saved: RoadAccidents114_x264.mp4 (16, 2048)
[11/350] Saved: RoadAccidents102_x264.mp4 (16, 2048)
[12/350] Saved: RoadAccidents072_x264.mp4 (16, 2048)
[13/350] Saved: RoadAccidents105_x264.mp4 (16, 2048)
[14/350] Saved: RoadAccidents099_x264.mp4 (16, 2048)
[15/350] Saved: RoadAccidents039_x264.mp4 (16, 2048)
[16/350] Saved: RoadAccidents019_x264.mp4 (16, 2048)
[17/350] Saved: RoadAccidents014_x264.mp4 (16, 2048)
[18/350] Saved: RoadAccidents003_x264.mp4 (16, 2048)
[19/350] Saved: RoadAccidents048_x264.mp4 (16, 2048)
[20/350] Saved: RoadAccidents106_x264.mp4 (16, 2048)
[21/350] Saved: RoadAccidents141_x264.mp4 (16, 2048)
[22/350] Saved: RoadAccidents069_x264.mp4 (16, 2048)
[23/350] Saved: RoadAccidents028_x264.mp4 (16, 2048)
[24/350] Saved: RoadAccidents006_x264.mp4 (16, 2048)
[25/350] Saved: RoadAccidents113_x264.mp4 (16, 2048)
[26/350] Saved: RoadAccidents080_x264.mp4 (16, 2048)
[27/350] Saved: RoadAccidents077_x264.mp4 (16, 2048)
[28/350] Saved: RoadAccidents004_x264.mp4 (16, 2048)
[29/350] Saved: RoadAccidents127_x264.mp4 (16, 2048)
[30/350] Saved: RoadAccidents066_x264.mp4 (16, 2048)
[31/350] Saved: RoadAccidents024_x264.mp4 (16, 2048)
[32/350] Saved: RoadAccidents081_x264.mp4 (16, 2048)
[33/350] Saved: RoadAccidents027_x264.mp4 (16, 2048)
[34/350] Saved: RoadAccidents010_x264.mp4 (16, 2048)
[35/350] Saved: RoadAccidents067_x264.mp4 (16, 2048)
[36/350] Saved: RoadAccidents116_x264.mp4 (16, 2048)
[37/350] Saved: RoadAccidents015_x264.mp4 (16, 2048)
[38/350] Saved: RoadAccidents001_x264.mp4 (16, 2048)
[39/350] Saved: RoadAccidents068_x264.mp4 (16, 2048)
[40/350] Saved: RoadAccidents058_x264.mp4 (16, 2048)
[41/350] Saved: RoadAccidents146_x264.mp4 (16, 2048)
[42/350] Saved: RoadAccidents101_x264.mp4 (16, 2048)
[43/350] Saved: RoadAccidents012_x264.mp4 (16, 2048)
[44/350] Saved: RoadAccidents044_x264.mp4 (16, 2048)
[45/350] Saved: RoadAccidents016_x264.mp4 (16, 2048)
[46/350] Saved: RoadAccidents143_x264.mp4 (16, 2048)
[47/350] Saved: RoadAccidents052_x264.mp4 (16, 2048)
[48/350] Saved: RoadAccidents023_x264.mp4 (16, 2048)
[49/350] Saved: RoadAccidents031_x264.mp4 (16, 2048)
[50/350] Saved: RoadAccidents050_x264.mp4 (16, 2048)
[51/350] Saved: RoadAccidents130_x264.mp4 (16, 2048)
[52/350] Saved: RoadAccidents002_x264.mp4 (16, 2048)
[53/350] Saved: RoadAccidents100_x264.mp4 (16, 2048)
[54/350] Saved: RoadAccidents103_x264.mp4 (16, 2048)
[55/350] Saved: RoadAccidents036_x264.mp4 (16, 2048)
[56/350] Saved: RoadAccidents091_x264.mp4 (16, 2048)
[57/350] Saved: RoadAccidents053_x264.mp4 (16, 2048)
[58/350] Saved: RoadAccidents097_x264.mp4 (16, 2048)
[59/350] Saved: RoadAccidents008_x264.mp4 (16, 2048)
[60/350] Saved: RoadAccidents122_x264.mp4 (16, 2048)
[61/350] Saved: RoadAccidents074_x264.mp4 (16, 2048)
[62/350] Saved: RoadAccidents126_x264.mp4 (16, 2048)
[63/350] Saved: RoadAccidents088_x264.mp4 (16, 2048)
[64/350] Saved: RoadAccidents051_x264.mp4 (16, 2048)
[65/350] Saved: RoadAccidents089_x264.mp4 (16, 2048)
[66/350] Saved: RoadAccidents032_x264.mp4 (16, 2048)
[67/350] Saved: RoadAccidents090_x264.mp4 (16, 2048)
[68/350] Saved: RoadAccidents043_x264.mp4 (16, 2048)
[69/350] Saved: RoadAccidents040_x264.mp4 (16, 2048)
[70/350] Saved: RoadAccidents149_x264.mp4 (16, 2048)
[71/350] Saved: RoadAccidents037_x264.mp4 (16, 2048)
[72/350] Saved: RoadAccidents034_x264.mp4 (16, 2048)
[73/350] Saved: RoadAccidents061_x264.mp4 (16, 2048)
[74/350] Saved: RoadAccidents151_x264.mp4 (16, 2048)
[75/350] Saved: RoadAccidents009_x264.mp4 (16, 2048)
[76/350] Saved: RoadAccidents104_x264.mp4 (16, 2048)
[77/350] Saved: RoadAccidents145_x264.mp4 (16, 2048)
[78/350] Saved: RoadAccidents018_x264.mp4 (16, 2048)
[79/350] Saved: RoadAccidents030_x264.mp4 (16, 2048)
[80/350] Saved: RoadAccidents112_x264.mp4 (16, 2048)
[81/350] Saved: RoadAccidents094_x264.mp4 (16, 2048)
[82/350] Saved: RoadAccidents047_x264.mp4 (16, 2048)
[83/350] Saved: RoadAccidents138_x264.mp4 (16, 2048)
[84/350] Saved: RoadAccidents098_x264.mp4 (16, 2048)
[85/350] Saved: RoadAccidents144_x264.mp4 (16, 2048)
[86/350] Saved: RoadAccidents011_x264.mp4 (16, 2048)
[87/350] Saved: RoadAccidents013_x264.mp4 (16, 2048)
[88/350] Saved: RoadAccidents096_x264.mp4 (16, 2048)
[89/350] Saved: RoadAccidents109_x264.mp4 (16, 2048)
[90/350] Saved: RoadAccidents038_x264.mp4 (16, 2048)
[91/350] Saved: RoadAccidents108_x264.mp4 (16, 2048)
[92/350] Saved: RoadAccidents121_x264.mp4 (16, 2048)
[93/350] Saved: RoadAccidents073_x264.mp4 (16, 2048)
[94/350] Saved: RoadAccidents118_x264.mp4 (16, 2048)
[95/350] Saved: RoadAccidents042_x264.mp4 (16, 2048)
[96/350] Saved: RoadAccidents136_x264.mp4 (16, 2048)
[97/350] Saved: RoadAccidents021_x264.mp4 (16, 2048)
[98/350] Saved: RoadAccidents142_x264.mp4 (16, 2048)
[99/350] Saved: RoadAccidents085_x264.mp4 (16, 2048)
[100/350] Saved: RoadAccidents025_x264.mp4 (16, 2048)
[101/350] Saved: RoadAccidents086_x264.mp4 (16, 2048)
[102/350] Saved: RoadAccidents123_x264.mp4 (16, 2048)
[103/350] Saved: RoadAccidents071_x264.mp4 (16, 2048)
[104/350] Saved: RoadAccidents148_x264.mp4 (16, 2048)
[105/350] Saved: RoadAccidents026_x264.mp4 (16, 2048)
[106/350] Saved: RoadAccidents041_x264.mp4 (16, 2048)
[107/350] Saved: RoadAccidents076_x264.mp4 (16, 2048)
[108/350] Saved: RoadAccidents079_x264.mp4 (16, 2048)
[109/350] Saved: RoadAccidents065_x264.mp4 (16, 2048)
[110/350] Saved: RoadAccidents147_x264.mp4 (16, 2048)
[111/350] Saved: RoadAccidents128_x264.mp4 (16, 2048)
[112/350] Saved: RoadAccidents046_x264.mp4 (16, 2048)
[113/350] Saved: RoadAccidents124_x264.mp4 (16, 2048)
[114/350] Saved: RoadAccidents054_x264.mp4 (16, 2048)
[115/350] Saved: RoadAccidents070_x264.mp4 (16, 2048)
[116/350] Saved: RoadAccidents135_x264.mp4 (16, 2048)
[117/350] Saved: RoadAccidents005_x264.mp4 (16, 2048)
[118/350] Saved: RoadAccidents017_x264.mp4 (16, 2048)
[119/350] Saved: RoadAccidents093_x264.mp4 (16, 2048)
[120/350] Saved: RoadAccidents117_x264.mp4 (16, 2048)
[121/350] Saved: RoadAccidents064_x264.mp4 (16, 2048)
[122/350] Saved: RoadAccidents075_x264.mp4 (16, 2048)
[123/350] Saved: RoadAccidents132_x264.mp4 (16, 2048)
[124/350] Saved: RoadAccidents059_x264.mp4 (16, 2048)
[125/350] Saved: RoadAccidents110_x264.mp4 (16, 2048)
[126/350] Saved: RoadAccidents084_x264.mp4 (16, 2048)
[127/350] Saved: RoadAccidents082_x264.mp4 (16, 2048)
[128/350] Saved: RoadAccidents055_x264.mp4 (16, 2048)
[129/350] Saved: RoadAccidents134_x264.mp4 (16, 2048)
[130/350] Saved: RoadAccidents140_x264.mp4 (16, 2048)
[131/350] Saved: RoadAccidents007_x264.mp4 (16, 2048)
[132/350] Saved: RoadAccidents115_x264.mp4 (16, 2048)
[133/350] Saved: RoadAccidents133_x264.mp4 (16, 2048)
[134/350] Saved: RoadAccidents060_x264.mp4 (16, 2048)
[135/350] Saved: RoadAccidents049_x264.mp4 (16, 2048)
[136/350] Saved: RoadAccidents063_x264.mp4 (16, 2048)
[137/350] Saved: RoadAccidents137_x264.mp4 (16, 2048)
[138/350] Saved: RoadAccidents119_x264.mp4 (16, 2048)
[139/350] Saved: RoadAccidents111_x264.mp4 (16, 2048)
[140/350] Saved: RoadAccidents139_x264.mp4 (16, 2048)
[141/350] Saved: RoadAccidents035_x264.mp4 (16, 2048)
[142/350] Saved: RoadAccidents020_x264.mp4 (16, 2048)
[143/350] Saved: RoadAccidents131_x264.mp4 (16, 2048)
[144/350] Saved: RoadAccidents150_x264.mp4 (16, 2048)
[145/350] Saved: RoadAccidents062_x264.mp4 (16, 2048)
[146/350] Saved: RoadAccidents029_x264.mp4 (16, 2048)
[147/350] Saved: RoadAccidents078_x264.mp4 (16, 2048)
[148/350] Saved: RoadAccidents120_x264.mp4 (16, 2048)
[149/350] Saved: RoadAccidents022_x264.mp4 (16, 2048)
[150/350] Saved: RoadAccidents095_x264.mp4 (16, 2048)
[151/350] Saved: Robbery102_x264.mp4 (16, 2048)
[152/350] Saved: Robbery056_x264.mp4 (16, 2048)
[153/350] Saved: Robbery057_x264.mp4 (16, 2048)
[154/350] Saved: Robbery015_x264.mp4 (16, 2048)
[155/350] Saved: Robbery050_x264.mp4 (16, 2048)
[156/350] Saved: Robbery064_x264.mp4 (16, 2048)
[157/350] Saved: Robbery035_x264.mp4 (16, 2048)
[158/350] Saved: Robbery026_x264.mp4 (16, 2048)
[159/350] Saved: Robbery109_x264.mp4 (16, 2048)
[160/350] Saved: Robbery008_x264.mp4 (16, 2048)
[161/350] Saved: Robbery045_x264.mp4 (16, 2048)
[162/350] Saved: Robbery068_x264.mp4 (16, 2048)
[163/350] Saved: Robbery012_x264.mp4 (16, 2048)
[164/350] Saved: Robbery128_x264.mp4 (16, 2048)
[165/350] Saved: Robbery014_x264.mp4 (16, 2048)
[166/350] Saved: Robbery123_x264.mp4 (16, 2048)
[167/350] Saved: Robbery031_x264.mp4 (16, 2048)
[168/350] Saved: Robbery097_x264.mp4 (16, 2048)
[169/350] Saved: Robbery037_x264.mp4 (16, 2048)
[170/350] Saved: Robbery138_x264.mp4 (16, 2048)
[171/350] Saved: Robbery049_x264.mp4 (16, 2048)
[172/350] Saved: Robbery100_x264.mp4 (16, 2048)
[173/350] Saved: Robbery070_x264.mp4 (16, 2048)
[174/350] Saved: Robbery137_x264.mp4 (16, 2048)
[175/350] Saved: Robbery039_x264.mp4 (16, 2048)
[176/350] Saved: Robbery018_x264.mp4 (16, 2048)
[177/350] Saved: Robbery115_x264.mp4 (16, 2048)
[178/350] Saved: Robbery147_x264.mp4 (16, 2048)
[179/350] Saved: Robbery075_x264.mp4 (16, 2048)
[180/350] Saved: Robbery036_x264.mp4 (16, 2048)
[181/350] Saved: Robbery089_x264.mp4 (16, 2048)
[182/350] Saved: Robbery104_x264.mp4 (16, 2048)
[183/350] Saved: Robbery041_x264.mp4 (16, 2048)
[184/350] Saved: Robbery086_x264.mp4 (16, 2048)
[185/350] Saved: Robbery119_x264.mp4 (16, 2048)
[186/350] Saved: Robbery038_x264.mp4 (16, 2048)
[187/350] Saved: Robbery141_x264.mp4 (16, 2048)
[188/350] Saved: Robbery016_x264.mp4 (16, 2048)
[189/350] Saved: Robbery046_x264.mp4 (16, 2048)
[190/350] Saved: Robbery069_x264.mp4 (16, 2048)
[191/350] Saved: Robbery060_x264.mp4 (16, 2048)
[192/350] Saved: Robbery113_x264.mp4 (16, 2048)
[193/350] Saved: Robbery129_x264.mp4 (16, 2048)
[194/350] Saved: Robbery094_x264.mp4 (16, 2048)
[195/350] Saved: Robbery040_x264.mp4 (16, 2048)
[196/350] Saved: Robbery028_x264.mp4 (16, 2048)
[197/350] Saved: Robbery084_x264.mp4 (16, 2048)
[198/350] Saved: Robbery105_x264.mp4 (16, 2048)
[199/350] Saved: Robbery140_x264.mp4 (16, 2048)
[200/350] Saved: Robbery139_x264.mp4 (16, 2048)
[201/350] Saved: Robbery053_x264.mp4 (16, 2048)
[202/350] Saved: Robbery125_x264.mp4 (16, 2048)
[203/350] Saved: Robbery127_x264.mp4 (16, 2048)
[204/350] Saved: Robbery082_x264.mp4 (16, 2048)
[205/350] Saved: Robbery009_x264.mp4 (16, 2048)
[206/350] Saved: Robbery132_x264.mp4 (16, 2048)
[207/350] Saved: Robbery054_x264.mp4 (16, 2048)
[208/350] Saved: Robbery130_x264.mp4 (16, 2048)
[209/350] Saved: Robbery122_x264.mp4 (16, 2048)
[210/350] Saved: Robbery098_x264.mp4 (16, 2048)
[211/350] Saved: Robbery023_x264.mp4 (16, 2048)
[212/350] Saved: Robbery150_x264.mp4 (16, 2048)
[213/350] Saved: Robbery063_x264.mp4 (16, 2048)
[214/350] Saved: Robbery051_x264.mp4 (16, 2048)
[215/350] Saved: Robbery121_x264.mp4 (16, 2048)
[216/350] Saved: Robbery124_x264.mp4 (16, 2048)
[217/350] Saved: Robbery072_x264.mp4 (16, 2048)
[218/350] Saved: Robbery033_x264.mp4 (16, 2048)
[219/350] Saved: Robbery061_x264.mp4 (16, 2048)
[220/350] Saved: Robbery087_x264.mp4 (16, 2048)
[221/350] Saved: Robbery042_x264.mp4 (16, 2048)
[222/350] Saved: Robbery006_x264.mp4 (16, 2048)
[223/350] Saved: Robbery003_x264.mp4 (16, 2048)
[224/350] Saved: Robbery004_x264.mp4 (16, 2048)
[225/350] Saved: Robbery076_x264.mp4 (16, 2048)
[226/350] Saved: Robbery013_x264.mp4 (16, 2048)
[227/350] Saved: Robbery095_x264.mp4 (16, 2048)
[228/350] Saved: Robbery110_x264.mp4 (16, 2048)
[229/350] Saved: Robbery001_x264.mp4 (16, 2048)
[230/350] Saved: Robbery093_x264.mp4 (16, 2048)
[231/350] Saved: Robbery055_x264.mp4 (16, 2048)
[232/350] Saved: Robbery103_x264.mp4 (16, 2048)
[233/350] Saved: Robbery085_x264.mp4 (16, 2048)
[234/350] Saved: Robbery058_x264.mp4 (16, 2048)
[235/350] Saved: Robbery081_x264.mp4 (16, 2048)
[236/350] Saved: Robbery047_x264.mp4 (16, 2048)
[237/350] Saved: Robbery067_x264.mp4 (16, 2048)
[238/350] Saved: Robbery126_x264.mp4 (16, 2048)
[239/350] Saved: Robbery146_x264.mp4 (16, 2048)
[240/350] Saved: Robbery111_x264.mp4 (16, 2048)
[241/350] Saved: Robbery116_x264.mp4 (16, 2048)
[242/350] Saved: Robbery044_x264.mp4 (16, 2048)
[243/350] Saved: Robbery017_x264.mp4 (16, 2048)
[244/350] Saved: Robbery005_x264.mp4 (16, 2048)
[245/350] Saved: Robbery091_x264.mp4 (16, 2048)
[246/350] Saved: Robbery021_x264.mp4 (16, 2048)
[247/350] Saved: Robbery065_x264.mp4 (16, 2048)
[248/350] Saved: Robbery029_x264.mp4 (16, 2048)
[249/350] Saved: Robbery101_x264.mp4 (16, 2048)
[250/350] Saved: Robbery118_x264.mp4 (16, 2048)
[251/350] Saved: Robbery024_x264.mp4 (16, 2048)
[252/350] Saved: Robbery083_x264.mp4 (16, 2048)
[253/350] Saved: Robbery090_x264.mp4 (16, 2048)
[254/350] Saved: Robbery052_x264.mp4 (16, 2048)
[255/350] Saved: Robbery144_x264.mp4 (16, 2048)
[256/350] Saved: Robbery059_x264.mp4 (16, 2048)
[257/350] Saved: Robbery030_x264.mp4 (16, 2048)
[258/350] Saved: Robbery114_x264.mp4 (16, 2048)
[259/350] Saved: Robbery007_x264.mp4 (16, 2048)
[260/350] Saved: Robbery002_x264.mp4 (16, 2048)
[261/350] Saved: Robbery142_x264.mp4 (16, 2048)
[262/350] Saved: Robbery134_x264.mp4 (16, 2048)
[263/350] Saved: Robbery010_x264.mp4 (16, 2048)
[264/350] Saved: Robbery133_x264.mp4 (16, 2048)
[265/350] Saved: Robbery112_x264.mp4 (16, 2048)
[266/350] Saved: Robbery107_x264.mp4 (16, 2048)
[267/350] Saved: Robbery106_x264.mp4 (16, 2048)
[268/350] Saved: Robbery096_x264.mp4 (16, 2048)
[269/350] Saved: Robbery092_x264.mp4 (16, 2048)
[270/350] Saved: Robbery143_x264.mp4 (16, 2048)
[271/350] Saved: Robbery022_x264.mp4 (16, 2048)
[272/350] Saved: Robbery145_x264.mp4 (16, 2048)
[273/350] Saved: Robbery149_x264.mp4 (16, 2048)
[274/350] Saved: Robbery148_x264.mp4 (16, 2048)
[275/350] Saved: Robbery074_x264.mp4 (16, 2048)
[276/350] Saved: Robbery066_x264.mp4 (16, 2048)
[277/350] Saved: Robbery025_x264.mp4 (16, 2048)
[278/350] Saved: Robbery062_x264.mp4 (16, 2048)
[279/350] Saved: Robbery043_x264.mp4 (16, 2048)
[280/350] Saved: Robbery088_x264.mp4 (16, 2048)
[281/350] Saved: Robbery099_x264.mp4 (16, 2048)
[282/350] Saved: Robbery131_x264.mp4 (16, 2048)
[283/350] Saved: Robbery027_x264.mp4 (16, 2048)
[284/350] Saved: Robbery117_x264.mp4 (16, 2048)
[285/350] Saved: Robbery034_x264.mp4 (16, 2048)
[286/350] Saved: Robbery071_x264.mp4 (16, 2048)
[287/350] Saved: Robbery020_x264.mp4 (16, 2048)
[288/350] Saved: Robbery032_x264.mp4 (16, 2048)
[289/350] Saved: Robbery120_x264.mp4 (16, 2048)
[290/350] Saved: Robbery079_x264.mp4 (16, 2048)
[291/350] Saved: Robbery108_x264.mp4 (16, 2048)
[292/350] Saved: Robbery080_x264.mp4 (16, 2048)
[293/350] Saved: Robbery135_x264.mp4 (16, 2048)
[294/350] Saved: Robbery136_x264.mp4 (16, 2048)
[295/350] Saved: Robbery048_x264.mp4 (16, 2048)
[296/350] Saved: Robbery073_x264.mp4 (16, 2048)
[297/350] Saved: Robbery019_x264.mp4 (16, 2048)
[298/350] Saved: Robbery078_x264.mp4 (16, 2048)
[299/350] Saved: Robbery077_x264.mp4 (16, 2048)
[300/350] Saved: Robbery011_x264.mp4 (16, 2048)
[301/350] Saved: Shooting037_x264.mp4 (16, 2048)
[302/350] Saved: Shooting033_x264.mp4 (16, 2048)
[303/350] Saved: Shooting031_x264.mp4 (16, 2048)
[304/350] Saved: Shooting052_x264.mp4 (16, 2048)
[305/350] Saved: Shooting029_x264.mp4 (16, 2048)
[306/350] Saved: Shooting039_x264.mp4 (16, 2048)
[307/350] Saved: Shooting014_x264.mp4 (16, 2048)
[308/350] Saved: Shooting032_x264.mp4 (16, 2048)
[309/350] Saved: Shooting043_x264.mp4 (16, 2048)
[310/350] Saved: Shooting011_x264.mp4 (16, 2048)
[311/350] Saved: Shooting004_x264.mp4 (16, 2048)
[312/350] Saved: Shooting030_x264.mp4 (16, 2048)
[313/350] Saved: Shooting003_x264.mp4 (16, 2048)
[314/350] Saved: Shooting023_x264.mp4 (16, 2048)
[315/350] Saved: Shooting027_x264.mp4 (16, 2048)
[316/350] Saved: Shooting008_x264.mp4 (16, 2048)
[317/350] Saved: Shooting021_x264.mp4 (16, 2048)
[318/350] Saved: Shooting002_x264.mp4 (16, 2048)
[319/350] Saved: Shooting005_x264.mp4 (16, 2048)
[320/350] Saved: Shooting028_x264.mp4 (16, 2048)
[321/350] Saved: Shooting050_x264.mp4 (16, 2048)
[322/350] Saved: Shooting020_x264.mp4 (16, 2048)
[323/350] Saved: Shooting054_x264.mp4 (16, 2048)
[324/350] Saved: Shooting053_x264.mp4 (16, 2048)
[325/350] Saved: Shooting024_x264.mp4 (16, 2048)
[326/350] Saved: Shooting026_x264.mp4 (16, 2048)
[327/350] Saved: Shooting025_x264.mp4 (16, 2048)
[328/350] Saved: Shooting038_x264.mp4 (16, 2048)
[329/350] Saved: Shooting042_x264.mp4 (16, 2048)
[330/350] Saved: Shooting022_x264.mp4 (16, 2048)
[331/350] Saved: Shooting007_x264.mp4 (16, 2048)
[332/350] Saved: Shooting047_x264.mp4 (16, 2048)
[333/350] Saved: Shooting015_x264.mp4 (16, 2048)
[334/350] Saved: Shooting006_x264.mp4 (16, 2048)
[335/350] Saved: Shooting046_x264.mp4 (16, 2048)
[336/350] Saved: Shooting001_x264.mp4 (16, 2048)
[337/350] Saved: Shooting034_x264.mp4 (16, 2048)
[338/350] Saved: Shooting040_x264.mp4 (16, 2048)
[339/350] Saved: Shooting048_x264.mp4 (16, 2048)
[340/350] Saved: Shooting009_x264.mp4 (16, 2048)
[341/350] Saved: Shooting019_x264.mp4 (16, 2048)
[342/350] Saved: Shooting012_x264.mp4 (16, 2048)
[343/350] Saved: Shooting017_x264.mp4 (16, 2048)
[344/350] Saved: Shooting010_x264.mp4 (16, 2048)
[345/350] Saved: Shooting018_x264.mp4 (16, 2048)
[346/350] Saved: Shooting044_x264.mp4 (16, 2048)
[347/350] Saved: Shooting013_x264.mp4 (16, 2048)
[348/350] Saved: Shooting036_x264.mp4 (16, 2048)
[349/350] Saved: Shooting051_x264.mp4 (16, 2048)
[350/350] Saved: Shooting041_x264.mp4 (16, 2048)

Part 3 feature extraction finished.
status
Success    350
Name: count, dtype: int64
Metadata saved: /content/drive/MyDrive/UCF_Crime_Project/metadata/part3_metadata.csv
Processing log saved: /content/drive/MyDrive/UCF_Crime_Project/metadata/part3_processing_log.csv

**Part 4**

**Downlaod part 4 video**

In [41]:

from huggingface_hub import hf_hub_download
import os

repo_id = "jinmang2/ucf_crime"
file_name = "Anomaly-Videos-Part-4.zip"

zip_path = hf_hub_download(
    repo_id=repo_id,
    filename=file_name,
    repo_type="dataset",
    local_dir="/content/UCF_Crime"
)

print("Download completed:", os.path.exists(zip_path))
print("ZIP path:", zip_path)
print("File size (GB):", round(os.path.getsize(zip_path) / (1024**3), 2))

Anomaly-Videos-Part-4.zip: reconstructing file:   0%|          |  0.00B / 6.56GB

Anomaly-Videos-Part-4.zip: downloading bytes:           |  0.00B

Download completed: True
ZIP path: /content/UCF_Crime/Anomaly-Videos-Part-4.zip
File size (GB): 6.11

**Extract Part 4 videos**

In [42]:

import os
import zipfile

extract_path = "/content/UCF_Crime/videos"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

part4_folder = os.path.join(
    extract_path,
    "Anomaly-Videos-Part-4"
)

video_files = []

for root, dirs, files in os.walk(part4_folder):
    for file in files:
        if file.lower().endswith(".mp4"):
            video_files.append(os.path.join(root, file))

print("Part 4 folder exists:", os.path.exists(part4_folder))
print("Total extracted videos:", len(video_files))

print("\nFirst five videos:")
for video in video_files[:5]:
    print(video)

Part 4 folder exists: True
Total extracted videos: 200

First five videos:
/content/UCF_Crime/videos/Anomaly-Videos-Part-4/Vandalism/Vandalism038_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-4/Vandalism/Vandalism029_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-4/Vandalism/Vandalism024_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-4/Vandalism/Vandalism010_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-4/Vandalism/Vandalism050_x264.mp4

**Match Part 4 videos with the official training and testing lists**

In [43]:

import os
import pandas as pd

train_names = {
    line.strip().replace("\\", "/").split("/")[-1]
    for line in train_lines
    if line.strip()
}

test_names = {
    line.strip().replace("\\", "/").split("/")[-1]
    for line in test_lines
    if line.strip()
}

video_records = []

for video_path in video_files:
    video_name = os.path.basename(video_path)
    category = os.path.basename(os.path.dirname(video_path))

    if video_name in train_names:
        split = "train"
    elif video_name in test_names:
        split = "test"
    else:
        split = "unknown"

    video_records.append({
        "video_path": video_path,
        "video_name": video_name,
        "category": category,
        "split": split,
        "label": 1
    })

part4_df = pd.DataFrame(video_records)

print("Metadata shape:", part4_df.shape)

print("\nSplit counts:")
print(part4_df["split"].value_counts())

print("\nCategory and split counts:")
print(pd.crosstab(part4_df["category"], part4_df["split"]))

print("\nUnmatched videos:",
      (part4_df["split"] == "unknown").sum())

display(part4_df.head())

Metadata shape: (200, 5)

Split counts:
split
train    169
test      31
Name: count, dtype: int64

Category and split counts:
split        test  train
category
Shoplifting    21     29
Stealing        5     95
Vandalism       5     45

Unmatched videos: 0

,video_path,video_name,category,split,label
0,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Vandalism038_x264.mp4,Vandalism,train,1
1,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Vandalism029_x264.mp4,Vandalism,train,1
2,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Vandalism024_x264.mp4,Vandalism,train,1
3,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Vandalism010_x264.mp4,Vandalism,train,1
4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Vandalism050_x264.mp4,Vandalism,train,1

**Extract and save Part 4 features**

In [44]:

import os
import cv2
import numpy as np
import pandas as pd
import torch
from PIL import Image

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"

log_path = (
    "/content/drive/MyDrive/UCF_Crime_Project/"
    "metadata/part4_processing_log.csv"
)

metadata_path = (
    "/content/drive/MyDrive/UCF_Crime_Project/"
    "metadata/part4_metadata.csv"
)

num_frames = 16
results = []

# Save Part 4 metadata
part4_df.to_csv(metadata_path, index=False)

for index, row in part4_df.iterrows():

    video_path = row["video_path"]
    video_name = row["video_name"]
    category = row["category"]
    split = row["split"]

    save_folder = os.path.join(
        feature_root, split, category
    )
    os.makedirs(save_folder, exist_ok=True)

    feature_name = os.path.splitext(video_name)[0] + ".npy"
    feature_path = os.path.join(save_folder, feature_name)

    # Skip already saved valid features
    if os.path.exists(feature_path):
        try:
            saved_features = np.load(feature_path)

            if (saved_features.shape == (16, 2048)
                    and np.isfinite(saved_features).all()):

                status = "Success"
                print(
                    f"[{index + 1}/{len(part4_df)}] "
                    f"Already saved: {video_name}"
                )

                results.append({
                    "video_name": video_name,
                    "category": category,
                    "split": split,
                    "status": status
                })

                pd.DataFrame(results).to_csv(
                    log_path, index=False
                )
                continue

        except Exception:
            pass

    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    features_list = []

    if cap.isOpened() and total_frames >= num_frames:

        frame_indices = np.linspace(
            0, total_frames - 1, num_frames, dtype=int
        )

        for frame_index in frame_indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
            success, frame = cap.read()

            if not success:
                break

            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image = Image.fromarray(frame)
            image_tensor = preprocess(image).unsqueeze(0).to(device)

            with torch.no_grad():
                features = model(image_tensor)

            features = features.squeeze().cpu().numpy()
            features_list.append(features)

    cap.release()

    if len(features_list) == num_frames:
        video_features = np.array(
            features_list, dtype=np.float32
        )

        if np.isfinite(video_features).all():
            np.save(feature_path, video_features)
            status = "Success"
            print(
                f"[{index + 1}/{len(part4_df)}] "
                f"Saved: {video_name} {video_features.shape}"
            )
        else:
            status = "Failed: invalid feature values"
            print(f"Failed: {video_name}")
    else:
        status = "Failed: frame reading"
        print(f"Failed: {video_name}")

    results.append({
        "video_name": video_name,
        "category": category,
        "split": split,
        "status": status
    })

    # Save progress after each video
    pd.DataFrame(results).to_csv(log_path, index=False)

print("\nPart 4 feature extraction finished.")
print(pd.DataFrame(results)["status"].value_counts())
print("Metadata saved:", metadata_path)
print("Processing log saved:", log_path)

[1/200] Saved: Vandalism038_x264.mp4 (16, 2048)
[2/200] Saved: Vandalism029_x264.mp4 (16, 2048)
[3/200] Saved: Vandalism024_x264.mp4 (16, 2048)
[4/200] Saved: Vandalism010_x264.mp4 (16, 2048)
[5/200] Saved: Vandalism050_x264.mp4 (16, 2048)
[6/200] Saved: Vandalism037_x264.mp4 (16, 2048)
[7/200] Saved: Vandalism023_x264.mp4 (16, 2048)
[8/200] Saved: Vandalism040_x264.mp4 (16, 2048)
[9/200] Saved: Vandalism025_x264.mp4 (16, 2048)
[10/200] Saved: Vandalism011_x264.mp4 (16, 2048)
[11/200] Saved: Vandalism018_x264.mp4 (16, 2048)
[12/200] Saved: Vandalism048_x264.mp4 (16, 2048)
[13/200] Saved: Vandalism030_x264.mp4 (16, 2048)
[14/200] Saved: Vandalism007_x264.mp4 (16, 2048)
[15/200] Saved: Vandalism016_x264.mp4 (16, 2048)
[16/200] Saved: Vandalism019_x264.mp4 (16, 2048)
[17/200] Saved: Vandalism014_x264.mp4 (16, 2048)
[18/200] Saved: Vandalism044_x264.mp4 (16, 2048)
[19/200] Saved: Vandalism001_x264.mp4 (16, 2048)
[20/200] Saved: Vandalism021_x264.mp4 (16, 2048)
[21/200] Saved: Vandalism009_x264.mp4 (16, 2048)
[22/200] Saved: Vandalism008_x264.mp4 (16, 2048)
[23/200] Saved: Vandalism003_x264.mp4 (16, 2048)
[24/200] Saved: Vandalism033_x264.mp4 (16, 2048)
[25/200] Saved: Vandalism027_x264.mp4 (16, 2048)
[26/200] Saved: Vandalism028_x264.mp4 (16, 2048)
[27/200] Saved: Vandalism004_x264.mp4 (16, 2048)
[28/200] Saved: Vandalism031_x264.mp4 (16, 2048)
[29/200] Saved: Vandalism042_x264.mp4 (16, 2048)
[30/200] Saved: Vandalism017_x264.mp4 (16, 2048)
[31/200] Saved: Vandalism035_x264.mp4 (16, 2048)
[32/200] Saved: Vandalism034_x264.mp4 (16, 2048)
[33/200] Saved: Vandalism020_x264.mp4 (16, 2048)
[34/200] Saved: Vandalism005_x264.mp4 (16, 2048)
[35/200] Saved: Vandalism013_x264.mp4 (16, 2048)
[36/200] Saved: Vandalism046_x264.mp4 (16, 2048)
[37/200] Saved: Vandalism022_x264.mp4 (16, 2048)
[38/200] Saved: Vandalism012_x264.mp4 (16, 2048)
[39/200] Saved: Vandalism006_x264.mp4 (16, 2048)
[40/200] Saved: Vandalism036_x264.mp4 (16, 2048)
[41/200] Saved: Vandalism039_x264.mp4 (16, 2048)
[42/200] Saved: Vandalism049_x264.mp4 (16, 2048)
[43/200] Saved: Vandalism015_x264.mp4 (16, 2048)
[44/200] Saved: Vandalism032_x264.mp4 (16, 2048)
[45/200] Saved: Vandalism002_x264.mp4 (16, 2048)
[46/200] Saved: Vandalism026_x264.mp4 (16, 2048)
[47/200] Saved: Vandalism041_x264.mp4 (16, 2048)
[48/200] Saved: Vandalism045_x264.mp4 (16, 2048)
[49/200] Saved: Vandalism043_x264.mp4 (16, 2048)
[50/200] Saved: Vandalism047_x264.mp4 (16, 2048)
[51/200] Saved: Stealing095_x264.mp4 (16, 2048)
[52/200] Saved: Stealing013_x264.mp4 (16, 2048)
[53/200] Saved: Stealing093_x264.mp4 (16, 2048)
[54/200] Saved: Stealing092_x264.mp4 (16, 2048)
[55/200] Saved: Stealing007_x264.mp4 (16, 2048)
[56/200] Saved: Stealing016_x264.mp4 (16, 2048)
[57/200] Saved: Stealing030_x264.mp4 (16, 2048)
[58/200] Saved: Stealing006_x264.mp4 (16, 2048)
[59/200] Saved: Stealing044_x264.mp4 (16, 2048)
[60/200] Saved: Stealing020_x264.mp4 (16, 2048)
[61/200] Saved: Stealing004_x264.mp4 (16, 2048)
[62/200] Saved: Stealing106_x264.mp4 (16, 2048)
[63/200] Saved: Stealing070_x264.mp4 (16, 2048)
[64/200] Saved: Stealing110_x264.mp4 (16, 2048)
[65/200] Saved: Stealing089_x264.mp4 (16, 2048)
[66/200] Saved: Stealing067_x264.mp4 (16, 2048)
[67/200] Saved: Stealing053_x264.mp4 (16, 2048)
[68/200] Saved: Stealing068_x264.mp4 (16, 2048)
[69/200] Saved: Stealing066_x264.mp4 (16, 2048)
[70/200] Saved: Stealing079_x264.mp4 (16, 2048)
[71/200] Saved: Stealing114_x264.mp4 (16, 2048)
[72/200] Saved: Stealing035_x264.mp4 (16, 2048)
[73/200] Saved: Stealing018_x264.mp4 (16, 2048)
[74/200] Saved: Stealing087_x264.mp4 (16, 2048)
[75/200] Saved: Stealing058_x264.mp4 (16, 2048)
[76/200] Saved: Stealing027_x264.mp4 (16, 2048)
[77/200] Saved: Stealing055_x264.mp4 (16, 2048)
[78/200] Saved: Stealing109_x264.mp4 (16, 2048)
[79/200] Saved: Stealing104_x264.mp4 (16, 2048)
[80/200] Saved: Stealing080_x264.mp4 (16, 2048)
[81/200] Saved: Stealing063_x264.mp4 (16, 2048)
[82/200] Saved: Stealing105_x264.mp4 (16, 2048)
[83/200] Saved: Stealing021_x264.mp4 (16, 2048)
[84/200] Saved: Stealing037_x264.mp4 (16, 2048)
[85/200] Saved: Stealing032_x264.mp4 (16, 2048)
[86/200] Saved: Stealing102_x264.mp4 (16, 2048)
[87/200] Saved: Stealing017_x264.mp4 (16, 2048)
[88/200] Saved: Stealing097_x264.mp4 (16, 2048)
[89/200] Saved: Stealing022_x264.mp4 (16, 2048)
[90/200] Saved: Stealing028_x264.mp4 (16, 2048)
[91/200] Saved: Stealing024_x264.mp4 (16, 2048)
[92/200] Saved: Stealing107_x264.mp4 (16, 2048)
[93/200] Saved: Stealing086_x264.mp4 (16, 2048)
[94/200] Saved: Stealing014_x264.mp4 (16, 2048)
[95/200] Saved: Stealing008_x264.mp4 (16, 2048)
[96/200] Saved: Stealing002_x264.mp4 (16, 2048)
[97/200] Saved: Stealing101_x264.mp4 (16, 2048)
[98/200] Saved: Stealing051_x264.mp4 (16, 2048)
[99/200] Saved: Stealing043_x264.mp4 (16, 2048)
[100/200] Saved: Stealing065_x264.mp4 (16, 2048)
[101/200] Saved: Stealing010_x264.mp4 (16, 2048)
[102/200] Saved: Stealing072_x264.mp4 (16, 2048)
[103/200] Saved: Stealing083_x264.mp4 (16, 2048)
[104/200] Saved: Stealing060_x264.mp4 (16, 2048)
[105/200] Saved: Stealing100_x264.mp4 (16, 2048)
[106/200] Saved: Stealing073_x264.mp4 (16, 2048)
[107/200] Saved: Stealing050_x264.mp4 (16, 2048)
[108/200] Saved: Stealing048_x264.mp4 (16, 2048)
[109/200] Saved: Stealing091_x264.mp4 (16, 2048)
[110/200] Saved: Stealing012_x264.mp4 (16, 2048)
[111/200] Saved: Stealing025_x264.mp4 (16, 2048)
[112/200] Saved: Stealing077_x264.mp4 (16, 2048)
[113/200] Saved: Stealing061_x264.mp4 (16, 2048)
[114/200] Saved: Stealing088_x264.mp4 (16, 2048)
[115/200] Saved: Stealing015_x264.mp4 (16, 2048)
[116/200] Saved: Stealing057_x264.mp4 (16, 2048)
[117/200] Saved: Stealing052_x264.mp4 (16, 2048)
[118/200] Saved: Stealing112_x264.mp4 (16, 2048)
[119/200] Saved: Stealing031_x264.mp4 (16, 2048)
[120/200] Saved: Stealing069_x264.mp4 (16, 2048)
[121/200] Saved: Stealing062_x264.mp4 (16, 2048)
[122/200] Saved: Stealing023_x264.mp4 (16, 2048)
[123/200] Saved: Stealing019_x264.mp4 (16, 2048)
[124/200] Saved: Stealing071_x264.mp4 (16, 2048)
[125/200] Saved: Stealing049_x264.mp4 (16, 2048)
[126/200] Saved: Stealing054_x264.mp4 (16, 2048)
[127/200] Saved: Stealing046_x264.mp4 (16, 2048)
[128/200] Saved: Stealing103_x264.mp4 (16, 2048)
[129/200] Saved: Stealing075_x264.mp4 (16, 2048)
[130/200] Saved: Stealing045_x264.mp4 (16, 2048)
[131/200] Saved: Stealing047_x264.mp4 (16, 2048)
[132/200] Saved: Stealing003_x264.mp4 (16, 2048)
[133/200] Saved: Stealing026_x264.mp4 (16, 2048)
[134/200] Saved: Stealing081_x264.mp4 (16, 2048)
[135/200] Saved: Stealing059_x264.mp4 (16, 2048)
[136/200] Saved: Stealing108_x264.mp4 (16, 2048)
[137/200] Saved: Stealing029_x264.mp4 (16, 2048)
[138/200] Saved: Stealing111_x264.mp4 (16, 2048)
[139/200] Saved: Stealing042_x264.mp4 (16, 2048)
[140/200] Saved: Stealing113_x264.mp4 (16, 2048)
[141/200] Saved: Stealing036_x264.mp4 (16, 2048)
[142/200] Saved: Stealing009_x264.mp4 (16, 2048)
[143/200] Saved: Stealing098_x264.mp4 (16, 2048)
[144/200] Saved: Stealing011_x264.mp4 (16, 2048)
[145/200] Saved: Stealing094_x264.mp4 (16, 2048)
[146/200] Saved: Stealing074_x264.mp4 (16, 2048)
[147/200] Saved: Stealing082_x264.mp4 (16, 2048)
[148/200] Saved: Stealing084_x264.mp4 (16, 2048)
[149/200] Saved: Stealing078_x264.mp4 (16, 2048)
[150/200] Saved: Stealing096_x264.mp4 (16, 2048)
[151/200] Saved: Shoplifting026_x264.mp4 (16, 2048)
[152/200] Saved: Shoplifting001_x264.mp4 (16, 2048)
[153/200] Saved: Shoplifting044_x264.mp4 (16, 2048)
[154/200] Saved: Shoplifting025_x264.mp4 (16, 2048)
[155/200] Saved: Shoplifting030_x264.mp4 (16, 2048)
[156/200] Saved: Shoplifting031_x264.mp4 (16, 2048)
[157/200] Saved: Shoplifting005_x264.mp4 (16, 2048)
[158/200] Saved: Shoplifting009_x264.mp4 (16, 2048)
[159/200] Saved: Shoplifting017_x264.mp4 (16, 2048)
[160/200] Saved: Shoplifting007_x264.mp4 (16, 2048)
[161/200] Saved: Shoplifting029_x264.mp4 (16, 2048)
[162/200] Saved: Shoplifting008_x264.mp4 (16, 2048)
[163/200] Saved: Shoplifting024_x264.mp4 (16, 2048)
[164/200] Saved: Shoplifting050_x264.mp4 (16, 2048)
[165/200] Saved: Shoplifting040_x264.mp4 (16, 2048)
[166/200] Saved: Shoplifting022_x264.mp4 (16, 2048)
[167/200] Saved: Shoplifting013_x264.mp4 (16, 2048)
[168/200] Saved: Shoplifting032_x264.mp4 (16, 2048)
[169/200] Saved: Shoplifting053_x264.mp4 (16, 2048)
[170/200] Saved: Shoplifting003_x264.mp4 (16, 2048)
[171/200] Saved: Shoplifting019_x264.mp4 (16, 2048)
[172/200] Saved: Shoplifting006_x264.mp4 (16, 2048)
[173/200] Saved: Shoplifting047_x264.mp4 (16, 2048)
[174/200] Saved: Shoplifting052_x264.mp4 (16, 2048)
[175/200] Saved: Shoplifting028_x264.mp4 (16, 2048)
[176/200] Saved: Shoplifting014_x264.mp4 (16, 2048)
[177/200] Saved: Shoplifting033_x264.mp4 (16, 2048)
[178/200] Saved: Shoplifting037_x264.mp4 (16, 2048)
[179/200] Saved: Shoplifting034_x264.mp4 (16, 2048)
[180/200] Saved: Shoplifting038_x264.mp4 (16, 2048)
[181/200] Saved: Shoplifting010_x264.mp4 (16, 2048)
[182/200] Saved: Shoplifting036_x264.mp4 (16, 2048)
[183/200] Saved: Shoplifting012_x264.mp4 (16, 2048)
[184/200] Saved: Shoplifting016_x264.mp4 (16, 2048)
[185/200] Saved: Shoplifting015_x264.mp4 (16, 2048)
[186/200] Saved: Shoplifting043_x264.mp4 (16, 2048)
[187/200] Saved: Shoplifting049_x264.mp4 (16, 2048)
[188/200] Saved: Shoplifting054_x264.mp4 (16, 2048)
[189/200] Saved: Shoplifting048_x264.mp4 (16, 2048)
[190/200] Saved: Shoplifting020_x264.mp4 (16, 2048)
[191/200] Saved: Shoplifting041_x264.mp4 (16, 2048)
[192/200] Saved: Shoplifting027_x264.mp4 (16, 2048)
[193/200] Saved: Shoplifting021_x264.mp4 (16, 2048)
[194/200] Saved: Shoplifting045_x264.mp4 (16, 2048)
[195/200] Saved: Shoplifting042_x264.mp4 (16, 2048)
[196/200] Saved: Shoplifting051_x264.mp4 (16, 2048)
[197/200] Saved: Shoplifting018_x264.mp4 (16, 2048)
[198/200] Saved: Shoplifting055_x264.mp4 (16, 2048)
[199/200] Saved: Shoplifting004_x264.mp4 (16, 2048)
[200/200] Saved: Shoplifting039_x264.mp4 (16, 2048)

Part 4 feature extraction finished.
status
Success    200
Name: count, dtype: int64
Metadata saved: /content/drive/MyDrive/UCF_Crime_Project/metadata/part4_metadata.csv
Processing log saved: /content/drive/MyDrive/UCF_Crime_Project/metadata/part4_processing_log.csv