<a href="https://colab.research.google.com/github/asirabm/cctv-video-anomaly-detection/blob/main/02_video_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Dataset Acquisition and Inspection**

In [ ]:
!pip install -q huggingface_hub

In [1]:
from huggingface_hub import HfApi

repo_id = "jinmang2/ucf_crime"
api = HfApi()
files = api.list_repo_files(
    repo_id=repo_id,
    repo_type="dataset"
)

print("Total files:", len(files))

for file in files:
    print(file)

Total files: 24
.gitattributes
Anomaly-Videos-Part-1.zip
Anomaly-Videos-Part-2.zip
Anomaly-Videos-Part-3.zip
Anomaly-Videos-Part-4.zip
Normal_Videos_for_Event_Recognition.zip
README.md
Testing_Normal_Videos.zip
Training-Normal-Videos-Part-1.zip
Training-Normal-Videos-Part-2.zip
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/ClassIDs.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/test_001.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/test_002.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/test_003.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/test_004.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/train_001.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/train_002.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/train_003.txt
UCF_Crimes-Train-Test-Split/Action_Recognition_splits/train_004.txt
UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/Anomaly_Test.txt
UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/Anomaly_Train.txt
UCF_Crimes-Train-Test-Split/Temporal_Anomaly_Annotation_for_Testing_Videos.txt
test.zip
ucf_crime.py

In [2]:
from huggingface_hub import hf_hub_download

readme_path = hf_hub_download(
    repo_id=repo_id,
    filename="README.md",
    repo_type="dataset"
)

with open(readme_path, "r", encoding="utf-8") as file:
    readme_text = file.read()

print(readme_text[:12000])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

---
license: cc0-1.0
task_categories:
- video-classification
language:
- en
pretty_name: ucf_crime
configs:
- config_name: anomaly
  data_files:
    - split: train
      path: "data/anomaly-train-*.tar" # 1610 samples (1081 + 24 + 120 + 118 + 125 + 142)
    - split: test
      path: "data/anomaly-test-*.tar" # 290 samples (119 + 4 + 48 + 50 + 43 + 26)
- config_name: event1
  data_files:
    - split: train
      path:
        - "data/*-event-train-*.tar" # common 28 samples (anomaly-train:anomaly-test=24:4)
        - "data/*-event-test-2-*.tar"
        - "data/*-event-test-3-*.tar"
        - "data/*-event-test-4-*.tar"
    - split: test
      path: "data/*-event-test-1-*.tar" # 168 samples (anomaly-train:anomaly-test=120:48)
- config_name: event2
  data_files:
    - split: train
      path:
        - "data/*-event-train-*.tar"
        - "data/*-event-test-1-*.tar"
        - "data/*-event-test-3-*.tar"
        - "data/*-event-test-4-*.tar"
    - split: test
      path: "data/*-event-test-2-*.tar" # 168 samples (anomaly-train:anomaly-test=118:50)
- config_name: event3
  data_files:
    - split: train
      path:
        - "data/*-event-train-*.tar"
        - "data/*-event-test-1-*.tar"
        - "data/*-event-test-2-*.tar"
        - "data/*-event-test-4-*.tar"
    - split: test
      path: "data/*-event-test-3-*.tar" # 168 samples (anomaly-train:anomaly-test=125:43)
- config_name: event4
  data_files:
    - split: train
      path:
        - "data/*-event-train-*.tar"
        - "data/*-event-test-1-*.tar"
        - "data/*-event-test-2-*.tar"
        - "data/*-event-test-3-*.tar"
    - split: test
      path: "data/*-event-test-4-*.tar" # 168 samples (anomaly-train:anomaly-test=142:26)
size_categories:
- 10M<n<100M
---


# UCF-Crime Dataset (WebDataset Format)

이 데이터셋은 [UCF-Crime](https://www.crcv.ucf.edu/projects/real-world/) 데이터셋을 Hugging Face `datasets` 라이브러리의 스트리밍 기능을 위해 WebDataset(TAR Sharding) 형식으로 변환한 버전입니다.
100GB 이상의 대규모 비디오 데이터를 효율적으로 로드할 수 있습니다.

## Dataset Description
- **Homepage:** [CRCV UCF-Crime](https://www.crcv.ucf.edu/projects/real-world/)
- **Paper:** [Real-world Anomaly Detection in Surveillance Videos](https://arxiv.org/abs/1801.04264)


```python
from datasets import load_dataset

# Anomaly Detection 설정 로드
dataset = load_dataset("your_id/ucf_crime", "anomaly_detection", split="train", streaming=True)

for sample in dataset:
    video_path = sample["mp4"]
    label = sample["json"]["event"]
    print(f"Video loaded: {video_path}, Label: {label}")
    break
```

```
@InProceedings{Sultani_2018_CVPR,
    author={Sultani, Waqas and Chen, Chen and Shah, Mubarak},
    title={Real-World Anomaly Detection in Surveillance Videos},
    booktitle={The IEEE Conference on Computer Vision and Pattern Recognition (CVPR)},
    month={June},
    year={2018},
}
```

**Create the Drive folders to store npy files**

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [4]:
from google.colab import drive
import os

drive.mount('/content/drive')

project_path = '/content/drive/MyDrive/UCF_Crime_Project'

os.makedirs(project_path + '/features/train', exist_ok=True)
os.makedirs(project_path + '/features/test', exist_ok=True)
os.makedirs(project_path + '/metadata', exist_ok=True)

print("Project folders are ready.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project folders are ready.

In [5]:
from huggingface_hub import hf_hub_download

repo_id = "jinmang2/ucf_crime"
file_name = "Anomaly-Videos-Part-1.zip"

zip_path = hf_hub_download(
    repo_id=repo_id,
    filename=file_name,
    repo_type="dataset",
    local_dir="/content/UCF_Crime"
)

print("sucessfully Downloded.")

Anomaly-Videos-Part-1.zip: reconstructing file:   0%|          |  0.00B / 6.27GB

Anomaly-Videos-Part-1.zip: downloading bytes:           |  0.00B

sucessfully Downloded.

**Insepect Downloaded folder part 1**

In [6]:
import zipfile

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    files = zip_ref.namelist()

print("Total files in ZIP:", len(files))

print("First 30 files:")
for file in files[:30]:
    print(file)

Total files in ZIP: 205
First 30 files:
Anomaly-Videos-Part-1/
Anomaly-Videos-Part-1/Abuse/
Anomaly-Videos-Part-1/Abuse/Abuse041_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse037_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse012_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse001_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse048_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse003_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse006_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse020_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse018_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse025_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse029_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse042_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse032_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse045_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse049_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse026_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse044_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse031_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse005_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse015_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse038_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse033_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse047_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse008_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse010_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse007_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse022_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse028_x264.mp4

**count the video file**

In [7]:
video_files = [
    file for file in files
    if file.lower().endswith('.mp4')
]

print("Total video files:", len(video_files))

print("\nFirst 10 video files:")
for file in video_files[:10]:
    print(file)

Total video files: 200

First 10 video files:
Anomaly-Videos-Part-1/Abuse/Abuse041_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse037_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse012_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse001_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse048_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse003_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse006_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse020_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse018_x264.mp4
Anomaly-Videos-Part-1/Abuse/Abuse025_x264.mp4

**Inspect non video files **

In [8]:
other_files = [
    file for file in files
    if not file.lower().endswith('.mp4')
]

print("Other entries:", len(other_files))

for file in other_files:
    print(file)

Other entries: 5
Anomaly-Videos-Part-1/
Anomaly-Videos-Part-1/Abuse/
Anomaly-Videos-Part-1/Assault/
Anomaly-Videos-Part-1/Arrest/
Anomaly-Videos-Part-1/Arson/

**Extract the videos from zip file **

In [9]:
import zipfile
import os

extract_path = "/content/UCF_Crime/videos"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction completed.")
print("Videos extracted to:", extract_path)

Extraction completed.
Videos extracted to: /content/UCF_Crime/videos

**Check the extracted videos**

In [10]:
import os

video_root = "/content/UCF_Crime/videos/Anomaly-Videos-Part-1"

extracted_videos = []

for root, dirs, filenames in os.walk(video_root):
    for filename in filenames:
        if filename.lower().endswith(".mp4"):
            extracted_videos.append(
                os.path.join(root, filename)
            )

print("Extracted MP4 videos:", len(extracted_videos))

print("\nFirst 10 videos:")
for video in extracted_videos[:10]:
    print(video)

Extracted MP4 videos: 200

First 10 videos:
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse017_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse030_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse003_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse016_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse015_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse011_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse024_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse037_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse048_x264.mp4
/content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse025_x264.mp4

**Count videos in each category**

In [11]:
from collections import Counter
import os

category_counts = Counter()

for video in extracted_videos:
    category = os.path.basename(os.path.dirname(video))
    category_counts[category] += 1

print("Videos in each category:")

for category, count in sorted(category_counts.items()):
    print(f"{category}: {count}")

print("Total videos:", sum(category_counts.values()))

Videos in each category:
Abuse: 50
Arrest: 50
Arson: 50
Assault: 50
Total videos: 200

**Download the official split files**

In [12]:
from huggingface_hub import hf_hub_download

repo_id = "jinmang2/ucf_crime"
split_folder = "UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/"

# downloading train split
train_split_path = hf_hub_download(
    repo_id=repo_id,
    filename=split_folder + "Anomaly_Train.txt",
    repo_type="dataset"
)
# downloading test splits
test_split_path = hf_hub_download(
    repo_id=repo_id,
    filename=split_folder + "Anomaly_Test.txt",
    repo_type="dataset"
)

print("Training split:", train_split_path)
print("Testing split:", test_split_path)

Anomaly_Train.txt:   0%|          | 0.00/70.4k [00:00<?, ?B/s]

Anomaly_Test.txt:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Training split: /root/.cache/huggingface/hub/datasets--jinmang2--ucf_crime/snapshots/6ea2a8930c6d625539b74804aa6e895c3c9d7dc5/UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/Anomaly_Train.txt
Testing split: /root/.cache/huggingface/hub/datasets--jinmang2--ucf_crime/snapshots/6ea2a8930c6d625539b74804aa6e895c3c9d7dc5/UCF_Crimes-Train-Test-Split/Anomaly_Detection_splits/Anomaly_Test.txt

**Identify training and testing videos**

In [13]:

with open(train_split_path, "r") as f:
    train_lines = [line.strip() for line in f if line.strip()]

with open(test_split_path, "r") as f:
    test_lines = [line.strip() for line in f if line.strip()]


train_names = {line.split("/")[-1].replace("\\", "/") for line in train_lines}
test_names = {line.split("/")[-1].replace("\\", "/") for line in test_lines}


train_videos = []
test_videos = []
unmatched_videos = []

for video in extracted_videos:
    video_name = os.path.basename(video)

    if video_name in train_names:
        train_videos.append(video)
    elif video_name in test_names:
        test_videos.append(video)
    else:
        unmatched_videos.append(video)


print("Training videos:", len(train_videos))
print("Testing videos:", len(test_videos))
print("Unmatched videos:", len(unmatched_videos))

Training videos: 181
Testing videos: 19
Unmatched videos: 0

**Creating dataframe to store metadata of part 1 video file**

In [14]:
import pandas as pd
import os

video_records = []

for video in train_videos:
    video_records.append({
        "video_path": video,
        "video_name": os.path.basename(video),
        "category": os.path.basename(os.path.dirname(video)),
        "split": "train",
        "label": 1
    })

for video in test_videos:
    video_records.append({
        "video_path": video,
        "video_name": os.path.basename(video),
        "category": os.path.basename(os.path.dirname(video)),
        "split": "test",
        "label": 1
    })

part1_df = pd.DataFrame(video_records)

print("Metadata shape:", part1_df.shape)
display(part1_df.head())

Metadata shape: (200, 5)

,video_path,video_name,category,split,label
0,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Abuse017_x264.mp4,Abuse,train,1
1,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Abuse003_x264.mp4,Abuse,train,1
2,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Abuse016_x264.mp4,Abuse,train,1
3,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Abuse015_x264.mp4,Abuse,train,1
4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Abuse011_x264.mp4,Abuse,train,1

**Prepare Pre-Trained ResNet50 to extract information from frames**

In [15]:
import torch
from torchvision import models, transforms


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


weights = models.ResNet50_Weights.DEFAULT
model = models.resnet50(weights=weights)

# Removing the final classification layer
model = torch.nn.Sequential(*list(model.children())[:-1])

# Set the model to evaluation mode, becoz model is already trained
model = model.to(device)
model.eval()

# Image preprocessing required by the pretrained weights,
## these weights handles the required operations, including resizing, cropping, converting the image to a tensor, and normalising its values.
preprocess = weights.transforms()

print("ResNet50 is ready.")
print("Device:", device)

Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 178MB/s]

ResNet50 is ready.
Device: cuda

**Testing ResNet50 to extract information from a video's frame**

In [16]:
import cv2
import numpy as np
import torch
from PIL import Image

# select the first video from traing set
video_path = train_videos[0]

# open the slecetd video
cap = cv2.VideoCapture(video_path)

# Read the first frame of the sopend video
success, frame = cap.read()
cap.release()

if success:
    # Convert OpenCV BGR image to RGB, bcoz OpenCV read images in BGR order
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    image = Image.fromarray(frame)

    # Apply ResNet50 preprocessing
    image_tensor = preprocess(image).unsqueeze(0).to(device)

    # Extract features
    with torch.no_grad():
        features = model(image_tensor)

    # Convert features to a NumPy array
    features = features.squeeze().cpu().numpy()

    print("Video:", video_path)
    print("Feature shape:", features.shape)
    print("Feature data type:", features.dtype)
else:
    print("Could not read the video frame.")

Video: /content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse017_x264.mp4
Feature shape: (2048,)
Feature data type: float32

**Extracting features from 16 selected frames of one video.**

In [17]:
import cv2
import numpy as np
import torch
from PIL import Image

video_path = train_videos[0]
num_frames = 16

cap = cv2.VideoCapture(video_path)
# get total frames of the video
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

if total_frames > 0:
    # Select 16 frames acrosss the video
    frame_indices = np.linspace(
        0, total_frames - 1, num_frames, dtype=int
    )

    video_features = []
#process each frames
    for frame_index in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
        success, frame = cap.read()

        if not success:
            continue

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(frame)
        image_tensor = preprocess(image).unsqueeze(0).to(device)

        with torch.no_grad():
            features = model(image_tensor)

        features = features.squeeze().cpu().numpy()
        video_features.append(features)

cap.release()

video_features = np.array(video_features, dtype=np.float32)

print("Video:", video_path)
print("Total frames in video:", total_frames)
print("Frames successfully processed:", len(video_features))
print("Feature shape:", video_features.shape)

Video: /content/UCF_Crime/videos/Anomaly-Videos-Part-1/Abuse/Abuse017_x264.mp4
Total frames in video: 1920
Frames successfully processed: 16
Feature shape: (16, 2048)

**Save the extracted features in Google Drive (Selected video's frame)**

In [18]:
import os
import numpy as np

# Create a folder for the test features
save_folder = "/content/drive/MyDrive/UCF_Crime_Project/features/train/Assault"
os.makedirs(save_folder, exist_ok=True)

# Save the features using the original video filename
feature_name = os.path.splitext(os.path.basename(video_path))[0] + ".npy"
feature_path = os.path.join(save_folder, feature_name)

np.save(feature_path, video_features)

print("Features saved to:", feature_path)
print("File exists:", os.path.exists(feature_path))

Features saved to: /content/drive/MyDrive/UCF_Crime_Project/features/train/Assault/Abuse017_x264.npy
File exists: True

**Load the saved features and verify them**

In [ ]:
saved_features = np.load(feature_path)

print("Loaded feature shape:", saved_features.shape)
print("Data type:", saved_features.dtype)
print("All values are finite:", np.isfinite(saved_features).all())

Loaded feature shape: (16, 2048)
Data type: float32
All values are finite: True

**Create a metadata table for Part 1**

In [ ]:
import os
import pandas as pd

video_records = []

for video in extracted_videos:
    video_name = os.path.basename(video)
    category = os.path.basename(os.path.dirname(video))

    if video in train_videos:
        split = "train"
    elif video in test_videos:
        split = "test"
    else:
        split = "unknown"

    video_records.append({
        "video_name": video_name,
        "video_path": video,
        "category": category,
        "split": split
    })

video_df = pd.DataFrame(video_records)

print("Total videos:", len(video_df))
print("\nVideos by split:")
print(video_df["split"].value_counts())

print("\nVideos by category and split:")
print(pd.crosstab(video_df["category"], video_df["split"]))

video_df.head()

Total videos: 200

Videos by split:
split
train    181
test      19
Name: count, dtype: int64

Videos by category and split:
split     test  train
category
Abuse        2     48
Arrest       5     45
Arson        9     41
Assault      3     47

,video_name,video_path,category,split
0,Assault036_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train
1,Assault047_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train
2,Assault045_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train
3,Assault041_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train
4,Assault006_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,test

**Check the category names**

In [ ]:
print("Categories in Part 1:")
print(sorted(video_df["category"].unique()))

Categories in Part 1:
['Abuse', 'Arrest', 'Arson', 'Assault']

**Add labels and save the metadata**

In [ ]:
# based on previous cell output all videos in Part 1 belong to anomaly categories
video_df["label"] = 1

# Save the metadata in Google Drive
metadata_path = (
    "/content/drive/MyDrive/UCF_Crime_Project/"
    "metadata/part1_metadata.csv"
)

video_df.to_csv(metadata_path, index=False)

print("Metadata saved successfully.")
print("File location:", metadata_path)

print("\nLabel counts:")
print(video_df["label"].value_counts())

video_df.head()

Metadata saved successfully.
File location: /content/drive/MyDrive/UCF_Crime_Project/metadata/part1_metadata.csv

Label counts:
label
1    200
Name: count, dtype: int64

,video_name,video_path,category,split,label
0,Assault036_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train,1
1,Assault047_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train,1
2,Assault045_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train,1
3,Assault041_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,train,1
4,Assault006_x264.mp4,/content/UCF_Crime/videos/Anomaly-Videos-Part-...,Assault,test,1

**Extract and save features for five videos for testing purpose**

In [ ]:
import os
import numpy as np
import cv2
import torch
from PIL import Image

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"

num_frames = 16
results = []

# Test with the first five videos
for _, row in video_df.head(5).iterrows():

    video_path = row["video_path"]
    video_name = row["video_name"]
    category = row["category"]
    split = row["split"]

    # Create the correct folder automatically
    save_folder = os.path.join(feature_root, split, category)
    os.makedirs(save_folder, exist_ok=True)

    # Create the output filename
    feature_name = os.path.splitext(video_name)[0] + ".npy"
    feature_path = os.path.join(save_folder, feature_name)

    # Skip files that have already been saved correctly
    if os.path.exists(feature_path):
        saved_features = np.load(feature_path)

        if saved_features.shape == (num_frames, 2048):
            print("Already saved:", video_name)
            results.append({
                "video_name": video_name,
                "status": "Already saved"
            })
            continue

    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total_frames < num_frames:
        cap.release()
        print("Not enough frames:", video_name)
        results.append({
            "video_name": video_name,
            "status": "Failed: not enough frames"
        })
        continue

    frame_indices = np.linspace(
        0, total_frames - 1, num_frames, dtype=int
    )

    features_list = []

    for frame_index in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
        success, frame = cap.read()

        if not success:
            break

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(frame)
        image_tensor = preprocess(image).unsqueeze(0).to(device)

        with torch.no_grad():
            features = model(image_tensor)

        features = features.squeeze().cpu().numpy()
        features_list.append(features)

    cap.release()

    if len(features_list) == num_frames:
        video_features = np.array(features_list, dtype=np.float32)
        np.save(feature_path, video_features)

        print("Saved:", video_name, video_features.shape)

        results.append({
            "video_name": video_name,
            "status": "Success"
        })

    else:
        print("Failed to process:", video_name)

        results.append({
            "video_name": video_name,
            "status": "Failed: frame reading"
        })

print("\nTest batch finished.")

Already saved: Assault036_x264.mp4
Saved: Assault047_x264.mp4 (16, 2048)
Saved: Assault045_x264.mp4 (16, 2048)
Saved: Assault041_x264.mp4 (16, 2048)
Saved: Assault006_x264.mp4 (16, 2048)

Test batch finished.

**Process all 200 videos in Part 1**

In [ ]:

import os
import cv2
import numpy as np
import pandas as pd
import torch
from PIL import Image

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"
log_path = "/content/drive/MyDrive/UCF_Crime_Project/metadata/part1_processing_log.csv"

num_frames = 16
results = []

total_videos = len(video_df)

for index, row in video_df.iterrows():

    video_path = row["video_path"]
    video_name = row["video_name"]
    category = row["category"]
    split = row["split"]

    save_folder = os.path.join(feature_root, split, category)
    os.makedirs(save_folder, exist_ok=True)

    feature_name = os.path.splitext(video_name)[0] + ".npy"
    feature_path = os.path.join(save_folder, feature_name)

    # Skip a video if its saved features are valid
    if os.path.exists(feature_path):
        try:
            saved_features = np.load(feature_path)

            if (saved_features.shape == (num_frames, 2048)
                    and np.isfinite(saved_features).all()):

                results.append({
                    "video_name": video_name,
                    "category": category,
                    "split": split,
                    "status": "Success"
                })

                print(f"[{index + 1}/{total_videos}] Already saved: {video_name}")
                continue

        except Exception:
            pass

    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if not cap.isOpened() or total_frames < num_frames:
        cap.release()

        results.append({
            "video_name": video_name,
            "category": category,
            "split": split,
            "status": "Failed: video unavailable or too short"
        })

        print(f"[{index + 1}/{total_videos}] Failed: {video_name}")
        continue

    frame_indices = np.linspace(
        0, total_frames - 1, num_frames, dtype=int
    )

    features_list = []

    for frame_index in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
        success, frame = cap.read()

        if not success:
            break

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(frame)
        image_tensor = preprocess(image).unsqueeze(0).to(device)

        with torch.no_grad():
            features = model(image_tensor)

        features = features.squeeze().cpu().numpy()
        features_list.append(features)

    cap.release()

    if len(features_list) == num_frames:
        video_features = np.array(features_list, dtype=np.float32)

        if np.isfinite(video_features).all():
            np.save(feature_path, video_features)

            status = "Success"
            print(
                f"[{index + 1}/{total_videos}] "
                f"Saved: {video_name} {video_features.shape}"
            )
        else:
            status = "Failed: invalid feature values"
            print(f"[{index + 1}/{total_videos}] Failed: {video_name}")
    else:
        status = "Failed: frame reading"
        print(f"[{index + 1}/{total_videos}] Failed: {video_name}")

    results.append({
        "video_name": video_name,
        "category": category,
        "split": split,
        "status": status
    })

    # Save the log after every video
    pd.DataFrame(results).to_csv(log_path, index=False)

print("\nPart 1 feature extraction finished.")
print(pd.DataFrame(results)["status"].value_counts())
print("Processing log:", log_path)

[1/200] Already saved: Assault036_x264.mp4
[2/200] Already saved: Assault047_x264.mp4
[3/200] Already saved: Assault045_x264.mp4
[4/200] Already saved: Assault041_x264.mp4
[5/200] Already saved: Assault006_x264.mp4
[6/200] Saved: Assault001_x264.mp4 (16, 2048)
[7/200] Saved: Assault010_x264.mp4 (16, 2048)
[8/200] Saved: Assault035_x264.mp4 (16, 2048)
[9/200] Saved: Assault034_x264.mp4 (16, 2048)
[10/200] Saved: Assault022_x264.mp4 (16, 2048)
[11/200] Saved: Assault049_x264.mp4 (16, 2048)
[12/200] Saved: Assault008_x264.mp4 (16, 2048)
[13/200] Saved: Assault029_x264.mp4 (16, 2048)
[14/200] Saved: Assault023_x264.mp4 (16, 2048)
[15/200] Saved: Assault039_x264.mp4 (16, 2048)
[16/200] Saved: Assault005_x264.mp4 (16, 2048)
[17/200] Saved: Assault007_x264.mp4 (16, 2048)
[18/200] Saved: Assault032_x264.mp4 (16, 2048)
[19/200] Saved: Assault040_x264.mp4 (16, 2048)
[20/200] Saved: Assault009_x264.mp4 (16, 2048)
[21/200] Saved: Assault012_x264.mp4 (16, 2048)
[22/200] Saved: Assault015_x264.mp4 (16, 2048)
[23/200] Saved: Assault025_x264.mp4 (16, 2048)
[24/200] Saved: Assault046_x264.mp4 (16, 2048)
[25/200] Saved: Assault004_x264.mp4 (16, 2048)
[26/200] Saved: Assault017_x264.mp4 (16, 2048)
[27/200] Saved: Assault019_x264.mp4 (16, 2048)
[28/200] Saved: Assault050_x264.mp4 (16, 2048)
[29/200] Saved: Assault013_x264.mp4 (16, 2048)
[30/200] Saved: Assault011_x264.mp4 (16, 2048)
[31/200] Saved: Assault018_x264.mp4 (16, 2048)
[32/200] Saved: Assault048_x264.mp4 (16, 2048)
[33/200] Saved: Assault016_x264.mp4 (16, 2048)
[34/200] Saved: Assault038_x264.mp4 (16, 2048)
[35/200] Saved: Assault028_x264.mp4 (16, 2048)
[36/200] Saved: Assault003_x264.mp4 (16, 2048)
[37/200] Saved: Assault030_x264.mp4 (16, 2048)
[38/200] Saved: Assault024_x264.mp4 (16, 2048)
[39/200] Saved: Assault051_x264.mp4 (16, 2048)
[40/200] Saved: Assault037_x264.mp4 (16, 2048)
[41/200] Saved: Assault052_x264.mp4 (16, 2048)
[42/200] Saved: Assault044_x264.mp4 (16, 2048)
[43/200] Saved: Assault020_x264.mp4 (16, 2048)
[44/200] Saved: Assault042_x264.mp4 (16, 2048)
[45/200] Saved: Assault027_x264.mp4 (16, 2048)
[46/200] Saved: Assault033_x264.mp4 (16, 2048)
[47/200] Saved: Assault031_x264.mp4 (16, 2048)
[48/200] Saved: Assault014_x264.mp4 (16, 2048)
[49/200] Saved: Assault026_x264.mp4 (16, 2048)
[50/200] Saved: Assault002_x264.mp4 (16, 2048)
[51/200] Saved: Arrest032_x264.mp4 (16, 2048)
[52/200] Saved: Arrest017_x264.mp4 (16, 2048)
[53/200] Saved: Arrest020_x264.mp4 (16, 2048)
[54/200] Saved: Arrest050_x264.mp4 (16, 2048)
[55/200] Saved: Arrest010_x264.mp4 (16, 2048)
[56/200] Saved: Arrest031_x264.mp4 (16, 2048)
[57/200] Saved: Arrest043_x264.mp4 (16, 2048)
[58/200] Saved: Arrest035_x264.mp4 (16, 2048)
[59/200] Saved: Arrest047_x264.mp4 (16, 2048)
[60/200] Saved: Arrest049_x264.mp4 (16, 2048)
[61/200] Saved: Arrest033_x264.mp4 (16, 2048)
[62/200] Saved: Arrest002_x264.mp4 (16, 2048)
[63/200] Saved: Arrest046_x264.mp4 (16, 2048)
[64/200] Saved: Arrest004_x264.mp4 (16, 2048)
[65/200] Saved: Arrest015_x264.mp4 (16, 2048)
[66/200] Saved: Arrest029_x264.mp4 (16, 2048)
[67/200] Saved: Arrest012_x264.mp4 (16, 2048)
[68/200] Saved: Arrest016_x264.mp4 (16, 2048)
[69/200] Saved: Arrest013_x264.mp4 (16, 2048)
[70/200] Saved: Arrest051_x264.mp4 (16, 2048)
[71/200] Saved: Arrest023_x264.mp4 (16, 2048)
[72/200] Saved: Arrest003_x264.mp4 (16, 2048)
[73/200] Saved: Arrest009_x264.mp4 (16, 2048)
[74/200] Saved: Arrest044_x264.mp4 (16, 2048)
[75/200] Saved: Arrest030_x264.mp4 (16, 2048)
[76/200] Saved: Arrest026_x264.mp4 (16, 2048)
[77/200] Saved: Arrest028_x264.mp4 (16, 2048)
[78/200] Saved: Arrest042_x264.mp4 (16, 2048)
[79/200] Saved: Arrest036_x264.mp4 (16, 2048)
[80/200] Saved: Arrest001_x264.mp4 (16, 2048)
[81/200] Saved: Arrest041_x264.mp4 (16, 2048)
[82/200] Saved: Arrest038_x264.mp4 (16, 2048)
[83/200] Saved: Arrest014_x264.mp4 (16, 2048)
[84/200] Saved: Arrest040_x264.mp4 (16, 2048)
[85/200] Saved: Arrest018_x264.mp4 (16, 2048)
[86/200] Saved: Arrest024_x264.mp4 (16, 2048)
[87/200] Saved: Arrest008_x264.mp4 (16, 2048)
[88/200] Saved: Arrest006_x264.mp4 (16, 2048)
[89/200] Saved: Arrest007_x264.mp4 (16, 2048)
[90/200] Saved: Arrest019_x264.mp4 (16, 2048)
[91/200] Saved: Arrest048_x264.mp4 (16, 2048)
[92/200] Saved: Arrest037_x264.mp4 (16, 2048)
[93/200] Saved: Arrest011_x264.mp4 (16, 2048)
[94/200] Saved: Arrest021_x264.mp4 (16, 2048)
[95/200] Saved: Arrest034_x264.mp4 (16, 2048)
[96/200] Saved: Arrest027_x264.mp4 (16, 2048)
[97/200] Saved: Arrest005_x264.mp4 (16, 2048)
[98/200] Saved: Arrest025_x264.mp4 (16, 2048)
[99/200] Saved: Arrest022_x264.mp4 (16, 2048)
[100/200] Saved: Arrest039_x264.mp4 (16, 2048)
[101/200] Saved: Arson025_x264.mp4 (16, 2048)
[102/200] Saved: Arson041_x264.mp4 (16, 2048)
[103/200] Saved: Arson029_x264.mp4 (16, 2048)
[104/200] Saved: Arson027_x264.mp4 (16, 2048)
[105/200] Saved: Arson015_x264.mp4 (16, 2048)
[106/200] Saved: Arson023_x264.mp4 (16, 2048)
[107/200] Saved: Arson020_x264.mp4 (16, 2048)
[108/200] Saved: Arson052_x264.mp4 (16, 2048)
[109/200] Saved: Arson048_x264.mp4 (16, 2048)
[110/200] Saved: Arson022_x264.mp4 (16, 2048)
[111/200] Saved: Arson037_x264.mp4 (16, 2048)
[112/200] Saved: Arson026_x264.mp4 (16, 2048)
[113/200] Saved: Arson016_x264.mp4 (16, 2048)
[114/200] Saved: Arson012_x264.mp4 (16, 2048)
[115/200] Saved: Arson051_x264.mp4 (16, 2048)
[116/200] Saved: Arson009_x264.mp4 (16, 2048)
[117/200] Saved: Arson008_x264.mp4 (16, 2048)
[118/200] Saved: Arson007_x264.mp4 (16, 2048)
[119/200] Saved: Arson005_x264.mp4 (16, 2048)
[120/200] Saved: Arson045_x264.mp4 (16, 2048)
[121/200] Saved: Arson039_x264.mp4 (16, 2048)
[122/200] Saved: Arson013_x264.mp4 (16, 2048)
[123/200] Saved: Arson053_x264.mp4 (16, 2048)
[124/200] Saved: Arson034_x264.mp4 (16, 2048)
[125/200] Saved: Arson036_x264.mp4 (16, 2048)
[126/200] Saved: Arson038_x264.mp4 (16, 2048)
[127/200] Saved: Arson050_x264.mp4 (16, 2048)
[128/200] Saved: Arson019_x264.mp4 (16, 2048)
[129/200] Saved: Arson047_x264.mp4 (16, 2048)
[130/200] Saved: Arson035_x264.mp4 (16, 2048)
[131/200] Saved: Arson001_x264.mp4 (16, 2048)
[132/200] Saved: Arson010_x264.mp4 (16, 2048)
[133/200] Saved: Arson040_x264.mp4 (16, 2048)
[134/200] Saved: Arson003_x264.mp4 (16, 2048)
[135/200] Saved: Arson030_x264.mp4 (16, 2048)
[136/200] Saved: Arson024_x264.mp4 (16, 2048)
[137/200] Saved: Arson046_x264.mp4 (16, 2048)
[138/200] Saved: Arson031_x264.mp4 (16, 2048)
[139/200] Saved: Arson017_x264.mp4 (16, 2048)
[140/200] Saved: Arson021_x264.mp4 (16, 2048)
[141/200] Saved: Arson011_x264.mp4 (16, 2048)
[142/200] Saved: Arson006_x264.mp4 (16, 2048)
[143/200] Saved: Arson028_x264.mp4 (16, 2048)
[144/200] Saved: Arson002_x264.mp4 (16, 2048)
[145/200] Saved: Arson014_x264.mp4 (16, 2048)
[146/200] Saved: Arson044_x264.mp4 (16, 2048)
[147/200] Saved: Arson042_x264.mp4 (16, 2048)
[148/200] Saved: Arson032_x264.mp4 (16, 2048)
[149/200] Saved: Arson018_x264.mp4 (16, 2048)
[150/200] Saved: Arson049_x264.mp4 (16, 2048)
[151/200] Saved: Abuse045_x264.mp4 (16, 2048)
[152/200] Saved: Abuse039_x264.mp4 (16, 2048)
[153/200] Saved: Abuse015_x264.mp4 (16, 2048)
[154/200] Saved: Abuse048_x264.mp4 (16, 2048)
[155/200] Saved: Abuse033_x264.mp4 (16, 2048)
[156/200] Saved: Abuse027_x264.mp4 (16, 2048)
[157/200] Saved: Abuse037_x264.mp4 (16, 2048)
[158/200] Saved: Abuse047_x264.mp4 (16, 2048)
[159/200] Saved: Abuse049_x264.mp4 (16, 2048)
[160/200] Saved: Abuse005_x264.mp4 (16, 2048)
[161/200] Saved: Abuse046_x264.mp4 (16, 2048)
[162/200] Saved: Abuse010_x264.mp4 (16, 2048)
[163/200] Saved: Abuse016_x264.mp4 (16, 2048)
[164/200] Saved: Abuse004_x264.mp4 (16, 2048)
[165/200] Saved: Abuse025_x264.mp4 (16, 2048)
[166/200] Saved: Abuse001_x264.mp4 (16, 2048)
[167/200] Saved: Abuse012_x264.mp4 (16, 2048)
[168/200] Saved: Abuse029_x264.mp4 (16, 2048)
[169/200] Saved: Abuse014_x264.mp4 (16, 2048)
[170/200] Saved: Abuse013_x264.mp4 (16, 2048)
[171/200] Saved: Abuse032_x264.mp4 (16, 2048)
[172/200] Saved: Abuse009_x264.mp4 (16, 2048)
[173/200] Saved: Abuse028_x264.mp4 (16, 2048)
[174/200] Saved: Abuse042_x264.mp4 (16, 2048)
[175/200] Saved: Abuse006_x264.mp4 (16, 2048)
[176/200] Saved: Abuse007_x264.mp4 (16, 2048)
[177/200] Saved: Abuse038_x264.mp4 (16, 2048)
[178/200] Saved: Abuse040_x264.mp4 (16, 2048)
[179/200] Saved: Abuse019_x264.mp4 (16, 2048)
[180/200] Saved: Abuse044_x264.mp4 (16, 2048)
[181/200] Saved: Abuse034_x264.mp4 (16, 2048)
[182/200] Saved: Abuse002_x264.mp4 (16, 2048)
[183/200] Saved: Abuse041_x264.mp4 (16, 2048)
[184/200] Saved: Abuse022_x264.mp4 (16, 2048)
[185/200] Saved: Abuse024_x264.mp4 (16, 2048)
[186/200] Saved: Abuse008_x264.mp4 (16, 2048)
[187/200] Saved: Abuse017_x264.mp4 (16, 2048)
[188/200] Saved: Abuse018_x264.mp4 (16, 2048)
[189/200] Saved: Abuse021_x264.mp4 (16, 2048)
[190/200] Saved: Abuse011_x264.mp4 (16, 2048)
[191/200] Saved: Abuse035_x264.mp4 (16, 2048)
[192/200] Saved: Abuse020_x264.mp4 (16, 2048)
[193/200] Saved: Abuse026_x264.mp4 (16, 2048)
[194/200] Saved: Abuse003_x264.mp4 (16, 2048)
[195/200] Saved: Abuse030_x264.mp4 (16, 2048)
[196/200] Saved: Abuse043_x264.mp4 (16, 2048)
[197/200] Saved: Abuse036_x264.mp4 (16, 2048)
[198/200] Saved: Abuse050_x264.mp4 (16, 2048)
[199/200] Saved: Abuse031_x264.mp4 (16, 2048)
[200/200] Saved: Abuse023_x264.mp4 (16, 2048)

Part 1 feature extraction finished.
status
Success    200
Name: count, dtype: int64
Processing log: /content/drive/MyDrive/UCF_Crime_Project/metadata/part1_processing_log.csv

**verify the saved files**

In [ ]:

import os
import numpy as np
from collections import Counter

feature_root = "/content/drive/MyDrive/UCF_Crime_Project/features"

feature_counts = Counter()
invalid_files = []

for split in ["train", "test"]:
    split_folder = os.path.join(feature_root, split)

    for category in os.listdir(split_folder):
        category_folder = os.path.join(split_folder, category)

        if not os.path.isdir(category_folder):
            continue

        for file_name in os.listdir(category_folder):
            if file_name.endswith(".npy"):
                feature_counts[split] += 1

                file_path = os.path.join(category_folder, file_name)
                features = np.load(file_path)

                if (features.shape != (16, 2048)
                        or not np.isfinite(features).all()):
                    invalid_files.append(file_path)

print("Training feature files:", feature_counts["train"])
print("Testing feature files:", feature_counts["test"])
print("Total feature files:", sum(feature_counts.values()))
print("Invalid feature files:", len(invalid_files))

Training feature files: 181
Testing feature files: 19
Total feature files: 200
Invalid feature files: 0